import type { ReactNode, ReactElement } from "react";
import * as Tooltip from "@radix-ui/react-tooltip";
import * as Popover from "@radix-ui/react-popover";
import * as Dialog from "@radix-ui/react-dialog";
import * as Tabs from "@radix-ui/react-tabs";
export function Hint({ children, text }: { children: ReactElement; text: string }) { return <Tooltip.Provider delayDuration={500}><Tooltip.Root><Tooltip.Trigger asChild>{children}</Tooltip.Trigger><Tooltip.Portal><Tooltip.Content className="ui-tooltip" sideOffset={6}>{text}</Tooltip.Content></Tooltip.Portal></Tooltip.Root></Tooltip.Provider>; }
export function UiPopover({ trigger, children }: { trigger: ReactElement; children: ReactNode }) { return <Popover.Root><Popover.Trigger asChild>{trigger}</Popover.Trigger><Popover.Portal><Popover.Content className="ui-popover" sideOffset={8} collisionPadding={8}>{children}</Popover.Content></Popover.Portal></Popover.Root>; }
export function UiDialog({ title, children, open, onOpenChange }: { title: string; children: ReactNode; open: boolean; onOpenChange(open: boolean): void }) { return <Dialog.Root open={open} onOpenChange={onOpenChange}><Dialog.Portal><Dialog.Overlay className="ui-dialog-overlay"/><Dialog.Content className="ui-dialog" aria-describedby={undefined} onOpenAutoFocus={event => { const input=document.querySelector<HTMLElement>('input[autofocus], textarea[autofocus], .command-search-input'); if(input){event.preventDefault();input.focus();} }}><header><Dialog.Title>{title}</Dialog.Title><Dialog.Close aria-label="关闭">×</Dialog.Close></header>{children}</Dialog.Content></Dialog.Portal></Dialog.Root>; }
export function UiTabs({ value, onChange, items }: { value: string; onChange(value: string): void; items: { id: string; label: string; content: ReactNode }[] }) { return <Tabs.Root value={value} onValueChange={onChange}><Tabs.List className="ui-tabs">{items.map(item => <Tabs.Trigger value={item.id} key={item.id}>{item.label}</Tabs.Trigger>)}</Tabs.List>{items.map(item => <Tabs.Content value={item.id} key={item.id}>{item.content}</Tabs.Content>)}</Tabs.Root>; }
