import test from "node:test";
import assert from "node:assert/strict";
import {ConnectionManager,type Signal,type ConnectionState} from "./connection.ts";
const settle=async()=>{for(let i=0;i<12;i++)await Promise.resolve()};
function fixture(){let now=0,id=0,reads=0,refreshes=0,stops=0;let failure:unknown;const timers=new Map<number,{at:number;run:()=>void}>();let receive!:(s:Signal)=>void,fail!:(e:unknown)=>void;const states:ConnectionState[]=[],batches:Array<readonly string[]|undefined>=[];
 const manager=new ConnectionManager({read:async()=>{reads++;if(failure)throw failure;return {cursor:1,epoch:"epoch"}},refresh:async targets=>{refreshes++;batches.push(targets)},state:value=>states.push(value),stream:(_c,_e,data,error)=>{receive=data;fail=error;return()=>{stops++}},setTimeout:(run,ms)=>{timers.set(++id,{at:now+ms,run});return id as unknown as ReturnType<typeof setTimeout>},clearTimeout:timer=>timers.delete(timer as unknown as number),now:()=>now});
 const advance=async(ms:number)=>{now+=ms;for(const [key,timer]of [...timers])if(timer.at<=now){timers.delete(key);timer.run();}await settle()};
 return {manager,states,batches,advance,receive:(type:string,sessionId="one")=>receive({type,cursor:1,epoch:"epoch",sessionId}),fail:(e=Error("stream closed"))=>fail(e),breakRead:(e:unknown)=>failure=e,counts:()=>({reads,refreshes,stops}),timers};}
test("heartbeats maintain health without scanning histories; token bursts are throttled",async()=>{const t=fixture();t.manager.start();await settle();for(let i=0;i<20;i++)t.receive("heartbeat");await t.advance(1000);assert.equal(t.counts().refreshes,0);for(let i=0;i<30;i++)t.receive("message-chunk");await t.advance(600);assert.equal(t.counts().refreshes,1);t.manager.stop()});
test("transient stream closure recovers once without an offline error; repeated stream failure uses polling",async()=>{const t=fixture();t.manager.start();await settle();t.fail();assert.equal(t.states.at(-1)?.phase,"reconnecting");await t.advance(1500);assert.equal(t.counts().reads,2);t.fail();await t.advance(6000);assert.deepEqual(t.states.at(-1),{phase:"online",mode:"polling",failures:0,detail:undefined});assert.equal(t.counts().reads,3);t.manager.stop()});
test("stopped and replaced connections ignore late stream errors and leave no retry timer",async()=>{const t=fixture();t.manager.start();await settle();t.manager.stop();const length=t.states.length;t.fail();await t.advance(40000);assert.equal(t.states.length,length);assert.equal(t.counts().reads,1);assert.equal(t.timers.size,0)});
test("concurrent parent/child signals retain both targets and global refresh dominates",async()=>{const t=fixture();t.manager.start();await settle();t.receive("message-chunk","parent");t.receive("subagent","child");await t.advance(600);assert.deepEqual(t.batches[0],["parent","child"]);t.manager.refresh();t.receive("message-chunk","child");await t.advance(600);assert.equal(t.batches[1],undefined);t.manager.stop()});
test("network failures use backoff and delay the offline notice; revocation blocks immediately",async()=>{const t=fixture();t.breakRead(Error("unreachable"));t.manager.start();await settle();assert.equal(t.states.at(-1)?.phase,"reconnecting");await t.advance(3000);assert.equal(t.states.at(-1)?.phase,"reconnecting");await t.advance(6000);assert.equal(t.states.at(-1)?.phase,"offline");t.manager.stop();const revoked=fixture();revoked.breakRead(Object.assign(Error("revoked"),{status:401}));revoked.manager.start();await settle();assert.equal(revoked.states.at(-1)?.phase,"blocked");assert.equal(revoked.timers.size,0);revoked.manager.stop()});
