import test from "node:test";import assert from "node:assert/strict";
import {draftKey,readDraft,preservePairingDrafts} from "./draft-store.ts";
import {rememberSession,permissionDescription,projectLabel,restoreFailedDraft} from "./experience-model.ts";
function storage(){const data=new Map<string,string>();return {data,getItem:async(key:string)=>data.get(key)??null,setItem:async(key:string,value:string)=>{data.set(key,value)},getAllKeys:async()=>[...data.keys()]};}
test("drafts survive re-pairing of the same computer without overwriting newer text",async()=>{const s=storage();const old={id:"old-device",fingerprint:"computer-one"};s.data.set("grok.remote.old-device.draft.session","legacy draft");assert.equal(await readDraft(s,old,"session"),"legacy draft");assert.equal(s.data.size,1);await preservePairingDrafts(s,old);assert.equal(await readDraft(s,{...old,id:"new-device"},"session"),"legacy draft");s.data.set(draftKey(old,"session"),"new edit");await preservePairingDrafts(s,old);assert.equal(await readDraft(s,old,"session"),"new edit");assert.equal(await readDraft(s,{id:"other",fingerprint:"computer-two"},"session"),null)});
test("recent navigation is unique and bounded; same-name projects remain distinguishable",()=>{assert.deepEqual(rememberSession(["a","b"],"b"),["b","a"]);assert.equal(rememberSession(Array.from({length:40},(_,i)=>String(i)),"new").length,30);const first={cwd:"C:/projects/demo",projectName:"demo"} as any,second={cwd:"C:/worktrees/demo",projectName:"demo"} as any;assert.ok(projectLabel(first,[first,second]).includes(first.cwd));assert.equal(projectLabel(first,[first]),"demo")});
test("permission display extracts actual action/input and retains legacy plain descriptions",()=>{assert.deepEqual(permissionDescription({summary:JSON.stringify({title:"Run command",rawInput:{command:"git status"}})}),{title:"Run command",detail:"git status"});assert.deepEqual(permissionDescription({summary:"Read project files"}),{title:"Read project files",detail:"Read project files"});assert.ok(permissionDescription({title:"Write file",rawInput:{file_path:"C:/demo/file.ts"}}).detail.endsWith("file.ts"))});
test("restoring a failed draft is idempotent and keeps newer work",()=>{assert.equal(restoreFailedDraft("request","request"),"request");const once=restoreFailedDraft("new work","request");assert.equal(restoreFailedDraft(once,"request"),once);assert.equal(once,"new work\n\nrequest");assert.deepEqual(permissionDescription({title:"Actual action",rawInput:"git status",summary:"{truncated"}),{title:"Actual action",detail:"git status"})});

test("mobile update notices compare only valid release versions",async()=>{const {mobileVersionIsNewer}=await import("./experience-model.ts");assert.equal(mobileVersionIsNewer("0.3.1","0.3.0"),true);assert.equal(mobileVersionIsNewer("0.3.0","0.3.0"),false);assert.equal(mobileVersionIsNewer("0.2.1","0.3.0"),false);assert.equal(mobileVersionIsNewer("unknown","0.3.0"),false);});
