import React from "react";
import { Icon, type IconName } from "./icons";
/** Legacy glyph names map onto the vector set so every IconButton renders the same everywhere. */
const glyphs:Record<string,IconName>={"‹":"back","×":"close","⋯":"more","＋":"add","☰":"menu","◫":"sessions","◷":"tasks","▧":"images","⚙":"settings"};
export function iconName(icon:string):IconName|undefined{return glyphs[icon]??(/^[a-z][A-Za-z]*$/.test(icon)?icon as IconName:undefined)}
import {ActivityIndicator,Pressable,Switch,Text,TextInput,View,StyleSheet,type StyleProp,type ViewStyle} from "react-native";
export const palettes={dark:{bg:"#121418",surface:"#1b1e24",raised:"#252a32",text:"#f1f3f7",muted:"#a2aab8",border:"#303741",accent:"#a5c3ff",accentSoft:"#a5c3ff1f",primary:"#4776d8",danger:"#ffaba6",dangerSoft:"#ffaba61a",warning:"#f0c36d",success:"#8bd7b8",overlay:"#000a"},light:{bg:"#f6f7fa",surface:"#ffffff",raised:"#eef1f6",text:"#1d2736",muted:"#5f6c82",border:"#dde2ea",accent:"#315db4",accentSoft:"#315db414",primary:"#3969c9",danger:"#ae3636",dangerSoft:"#ae36360f",warning:"#8a5a00",success:"#26775c",overlay:"#0007"}};
export type Theme=typeof palettes.dark;
/** Spacing, radius and type scale shared by every screen. New UI should not introduce other values. */
export const space={xs:4,sm:8,md:12,lg:16,xl:20,xxl:24} as const;
export const radius={sm:8,md:12,lg:16,pill:999} as const;
export const font={caption:12,small:13,body:15,input:16,title:17,heading:22} as const;
export type Tone="info"|"warning"|"danger"|"success";
const toneColor=(theme:Theme,tone:Tone)=>tone==="danger"?theme.danger:tone==="warning"?theme.warning:tone==="success"?theme.success:theme.accent;
export function Button({title,onPress,theme,primary=false,disabled=false,compact=false,danger=false,ghost=false,label}:{title:string;onPress:()=>void;theme:Theme;primary?:boolean;disabled?:boolean;compact?:boolean;danger?:boolean;ghost?:boolean;label?:string}){return <Pressable accessibilityRole="button" accessibilityLabel={label||title} accessibilityState={{disabled}} disabled={disabled} onPress={onPress} hitSlop={compact?4:0} style={({pressed})=>[ui.button,compact&&{paddingHorizontal:12,minHeight:38,paddingVertical:8},{backgroundColor:primary?theme.primary:ghost?"transparent":danger?theme.dangerSoft:theme.raised,opacity:disabled?.4:pressed?.75:1}]}><Text style={{fontSize:compact?font.small:font.body,fontWeight:"600",color:primary?"#fff":danger?theme.danger:theme.text}}>{title}</Text></Pressable>}
export function IconButton({label,icon,onPress,theme,active=false,disabled=false,badge}:{label:string;icon:string;onPress:()=>void;theme:Theme;active?:boolean;disabled?:boolean;badge?:number}){return <Pressable accessibilityRole="button" accessibilityLabel={label} accessibilityState={{disabled}} disabled={disabled} onPress={onPress} hitSlop={4} style={({pressed})=>[ui.icon,{opacity:disabled?.4:pressed?.6:1}]}>{iconName(icon)?<Icon name={iconName(icon)!} size={23} color={active?theme.accent:theme.text}/>:<Text style={{color:active?theme.accent:theme.text,fontSize:22}}>{icon}</Text>}{badge?<View style={[styles.badgeDot,{backgroundColor:theme.primary}]}><Text style={{color:"#fff",fontSize:10,fontWeight:"700"}}>{badge>99?"99+":badge}</Text></View>:null}</Pressable>}
export function Badge({text,theme,active=false,tone}:{text:string;theme:Theme;active?:boolean;tone?:Tone}){const color=tone?toneColor(theme,tone):active?theme.accent:theme.muted;return <View style={{backgroundColor:tone||active?theme.accentSoft:theme.raised,borderRadius:7,paddingHorizontal:8,paddingVertical:4,alignSelf:"flex-start"}}><Text style={{fontSize:11,color,fontWeight:"600"}}>{text}</Text></View>}
export function Card({children,theme,style}:{children:React.ReactNode;theme:Theme;style?:StyleProp<ViewStyle>}){return <View style={[ui.card,{backgroundColor:theme.surface,borderColor:theme.border},style]}>{children}</View>}
/** Filter / toggle pill. 36dp tall with hit slop so the touch target stays at 44dp. */
export function Chip({label,onPress,theme,selected=false,disabled=false,tone,accessibilityLabel}:{label:string;onPress?:()=>void;theme:Theme;selected?:boolean;disabled?:boolean;tone?:Tone;accessibilityLabel?:string}){const color=tone?toneColor(theme,tone):selected?theme.accent:theme.text;return <Pressable accessibilityRole="button" accessibilityLabel={accessibilityLabel||label} accessibilityState={{selected,disabled}} disabled={disabled||!onPress} onPress={onPress} hitSlop={4} style={({pressed})=>[styles.chip,{backgroundColor:selected||tone?theme.accentSoft:theme.raised,borderColor:selected?theme.accent:"transparent",opacity:disabled?.4:pressed?.7:1}]}><Text numberOfLines={1} style={{color,fontSize:font.small,fontWeight:selected?"700":"600"}}>{label}</Text></Pressable>}
/** Mutually exclusive tabs inside a screen. Equal-width segments, wraps to a scroller only when labels cannot fit. */
export function Segmented<T extends string>({items,value,onChange,theme}:{items:ReadonlyArray<readonly [T,string]>;value:T;onChange:(value:T)=>void;theme:Theme}){return <View accessibilityRole="tablist" style={[styles.segmented,{backgroundColor:theme.raised,minWidth:0}]}>{items.map(([id,label])=>{const selected=id===value;return <Pressable key={id} accessibilityRole="tab" accessibilityLabel={label} accessibilityState={{selected}} onPress={()=>onChange(id)} style={[styles.segment,{minWidth:0},selected&&{backgroundColor:theme.surface,borderColor:theme.border}]}><Text numberOfLines={1} style={{fontSize:font.small,fontWeight:selected?"700":"500",color:selected?theme.text:theme.muted}}>{label}</Text></Pressable>})}</View>}
/** One tappable settings / navigation row: title, optional detail line and trailing value or control. */
/** Switch in the app accent; platform defaults (Material teal on Android/web) clash with the blue UI. */
export function Toggle({theme,value,onValueChange,disabled=false,accessibilityLabel}:{theme:Theme;value:boolean;onValueChange:(value:boolean)=>void;disabled?:boolean;accessibilityLabel?:string}){return <Switch accessibilityLabel={accessibilityLabel} value={value} disabled={disabled} onValueChange={onValueChange} trackColor={{false:theme.border,true:theme.primary}} thumbColor="#ffffff" ios_backgroundColor={theme.border} {...({activeThumbColor:"#ffffff"} as object)}/>}
/** In-page header for a pushed sub-page: one row with an accent back chevron, the page title and an optional scope tag. */
export function SubpageHeader({theme,title,backLabel,onBack,tag}:{theme:Theme;title:string;backLabel:string;onBack:()=>void;tag?:string}){return <View style={[ui.row,{gap:space.xs,minHeight:44}]}><Pressable accessibilityRole="button" accessibilityLabel={backLabel} hitSlop={10} onPress={onBack} style={({pressed})=>({width:32,height:36,marginLeft:-6,alignItems:"center",justifyContent:"center",borderRadius:radius.sm,opacity:pressed?.5:1})}><Icon name="back" size={22} color={theme.accent}/></Pressable><Text accessibilityRole="header" numberOfLines={1} style={{flex:1,color:theme.text,fontSize:20,fontWeight:"700"}}>{title}</Text>{tag?<View style={{alignSelf:"center"}}><Badge theme={theme} text={tag}/></View>:null}</View>}
/** `action` rows run something immediately (accent title, no chevron); plain tappable rows navigate (chevron). */
/** Pill search box with a leading icon and a clear button; text stays at body size so it never outweighs the rows below. */
export function SearchField({theme,value,onChangeText,placeholder,accessibilityLabel,style}:{theme:Theme;value:string;onChangeText:(value:string)=>void;placeholder:string;accessibilityLabel:string;style?:StyleProp<ViewStyle>}){return <View style={[{flexDirection:"row",alignItems:"center",gap:space.sm,minHeight:42,paddingLeft:space.md,paddingRight:space.xs,borderRadius:radius.pill,borderWidth:1,borderColor:theme.border,backgroundColor:theme.surface},style]}><Icon name="search" size={17} color={theme.muted}/><TextInput accessibilityLabel={accessibilityLabel} value={value} onChangeText={onChangeText} placeholder={placeholder} placeholderTextColor={theme.muted} returnKeyType="search" style={{flex:1,minWidth:0,paddingVertical:8,fontSize:font.body,color:theme.text}}/>{value?<Pressable accessibilityRole="button" accessibilityLabel="清除搜索" hitSlop={8} onPress={()=>onChangeText("")} style={{width:32,height:32,alignItems:"center",justifyContent:"center"}}><Icon name="close" size={16} color={theme.muted}/></Pressable>:null}</View>}
export function ListRow({title,detail,value,onPress,right,theme,danger=false,disabled=false,chevron,action=false,accessibilityLabel}:{title:string;detail?:string;value?:string;onPress?:()=>void;right?:React.ReactNode;theme:Theme;danger?:boolean;disabled?:boolean;chevron?:boolean;action?:boolean;accessibilityLabel?:string}){const body=<><View style={{flex:1,gap:3}}><Text style={{color:danger?theme.danger:action?theme.accent:theme.text,fontSize:font.body,fontWeight:action||danger?"600":"500"}}>{title}</Text>{detail?<Text style={{color:theme.muted,fontSize:font.caption,lineHeight:18}}>{detail}</Text>:null}</View>{value?<Text numberOfLines={1} style={{color:theme.muted,fontSize:font.small,maxWidth:"45%"}}>{value}</Text>:null}{right}{(chevron??(Boolean(onPress)&&!action&&!danger))&&!right?<Icon name="forward" size={16} color={theme.muted}/>:null}</>;return onPress?<Pressable accessibilityRole="button" accessibilityLabel={accessibilityLabel||title} accessibilityState={{disabled}} disabled={disabled} onPress={onPress} style={({pressed})=>[styles.row,{opacity:disabled?.45:1,backgroundColor:pressed?theme.raised:"transparent"}]}>{body}</Pressable>:<View accessibilityLabel={accessibilityLabel} style={styles.row}>{body}</View>}
/** Grouped list: small caption title, rounded container, hairline dividers between rows. */
export function Section({title,footer,children,theme}:{title?:string;footer?:string;children:React.ReactNode;theme:Theme}){const rows=React.Children.toArray(children).filter(Boolean);return <View style={{gap:space.sm}}>{title?<Text style={[styles.caption,{color:theme.muted}]}>{title}</Text>:null}<View style={[styles.group,{backgroundColor:theme.surface,borderColor:theme.border}]}>{rows.map((row,index)=><View key={index} style={index?{borderTopWidth:StyleSheet.hairlineWidth,borderTopColor:theme.border}:undefined}>{row}</View>)}</View>{footer?<Text style={[ui.hint,{color:theme.muted,paddingHorizontal:space.xs}]}>{footer}</Text>:null}</View>}
/** Full-width status strip. Only one per tone should be visible; see status-model.ts for priority. */
export function Banner({text,tone="info",theme,action,onAction,onDismiss,onPress,busy=false}:{text:string;tone?:Tone;theme:Theme;action?:string;onAction?:()=>void;onDismiss?:()=>void;onPress?:()=>void;busy?:boolean}){const color=toneColor(theme,tone);const body=<>{busy?<ActivityIndicator size="small" color={color}/>:<View style={[styles.toneDot,{backgroundColor:color}]}/>}<Text selectable={!onPress} style={{flex:1,color:tone==="info"?theme.text:color,fontSize:font.small,lineHeight:19}}>{text}</Text>{action&&onAction?<Button compact title={action} theme={theme} onPress={onAction}/>:null}{onDismiss?<IconButton label="关闭提示" icon="×" theme={theme} onPress={onDismiss}/>:null}</>;return onPress?<Pressable accessibilityRole="button" accessibilityLabel={text} onPress={onPress} style={[styles.banner,{backgroundColor:tone==="danger"?theme.dangerSoft:theme.accentSoft}]}>{body}</Pressable>:<View accessibilityRole="alert" style={[styles.banner,{backgroundColor:tone==="danger"?theme.dangerSoft:theme.accentSoft}]}>{body}</View>}
export function EmptyState({title,hint,theme,action}:{title:string;hint?:string;theme:Theme;action?:React.ReactNode}){return <View style={ui.empty}><Text style={[ui.title,{color:theme.text,textAlign:"center"}]}>{title}</Text>{hint?<Text style={[ui.hint,{color:theme.muted,textAlign:"center"}]}>{hint}</Text>:null}{action}</View>}
export const ui=StyleSheet.create({button:{minHeight:44,paddingVertical:12,paddingHorizontal:16,borderRadius:radius.md,alignItems:"center",justifyContent:"center"},icon:{minWidth:44,minHeight:44,alignItems:"center",justifyContent:"center"},card:{borderWidth:1,borderRadius:radius.lg,padding:space.lg,gap:10},row:{flexDirection:"row",alignItems:"center",gap:9},field:{borderWidth:1,borderRadius:radius.md,minHeight:48,paddingHorizontal:14,paddingVertical:11,fontSize:font.input,textAlignVertical:"top"},section:{fontSize:font.small,fontWeight:"700",letterSpacing:.3,marginTop:12,marginBottom:10},heading:{fontSize:24,lineHeight:32,fontWeight:"700"},hint:{fontSize:font.small,lineHeight:20},nav:{flexDirection:"row",alignItems:"center",justifyContent:"space-around",borderTopWidth:1,paddingVertical:4},page:{flex:1},content:{padding:space.lg,gap:space.md,paddingBottom:space.xxl*2},title:{fontSize:font.title,fontWeight:"600",lineHeight:25},header:{paddingHorizontal:space.sm,paddingVertical:6,flexDirection:"row",alignItems:"center",gap:4,borderBottomWidth:1,minHeight:56},modal:{flex:1,justifyContent:"flex-end",backgroundColor:"#0007"},sheet:{maxHeight:"90%",paddingHorizontal:space.xl,paddingTop:space.sm,paddingBottom:space.lg,borderTopLeftRadius:24,borderTopRightRadius:24,gap:space.md},empty:{padding:36,alignItems:"center",gap:10}});
const styles=StyleSheet.create({chip:{minHeight:36,paddingHorizontal:14,borderRadius:radius.pill,borderWidth:1,alignItems:"center",justifyContent:"center"},segmented:{flexDirection:"row",borderRadius:radius.md,padding:3,gap:2},segment:{flex:1,minHeight:44,borderRadius:radius.sm+1,borderWidth:1,borderColor:"transparent",alignItems:"center",justifyContent:"center",paddingHorizontal:6},row:{flexDirection:"row",alignItems:"center",gap:space.md,minHeight:52,paddingHorizontal:space.lg,paddingVertical:space.md},group:{borderWidth:1,borderRadius:radius.lg,overflow:"hidden"},caption:{fontSize:font.caption,fontWeight:"700",letterSpacing:.4,paddingHorizontal:space.xs},banner:{flexDirection:"row",alignItems:"center",gap:space.sm,paddingLeft:space.lg,paddingRight:space.xs,minHeight:44,paddingVertical:4},toneDot:{width:7,height:7,borderRadius:4},badgeDot:{position:"absolute",top:6,right:4,minWidth:16,height:16,borderRadius:8,paddingHorizontal:3,alignItems:"center",justifyContent:"center"}});
