import {describe,it,expect,vi,afterEach}from"vitest";
import{mkdtemp,rm,readFile,mkdir,writeFile}from"node:fs/promises";
import{join}from"node:path";
import{tmpdir}from"node:os";
import{RemoteFiles}from"./remote-files";
import{RemoteWorkbenchService}from"./remote-workbench-service";
import{parseRemoteCommand}from"./remote-gateway-service";
import type{AppController}from"../app-controller";
import {MediaAccessService}from"./media-access-service";
import {sessionCacheKey}from"./media-cache-service";
const roots:string[]=[];afterEach(async()=>{for(const root of roots.splice(0))await rm(root,{recursive:true,force:true})});
const root=async()=>{const value=await mkdtemp(join(tmpdir(),"grok-mobile-contract-"));roots.push(value);return value};
describe("remote workbench contracts",()=>{
 it("accepts actual model/mode/effort configuration and rejects path or hidden operation fields",()=>{const base={operationId:Date.now()+"_model",sessionId:"session",action:"configure",revision:"a".repeat(64),modelId:"provider-model"};expect(parseRemoteCommand(base).modelId).toBe("provider-model");expect(()=>parseRemoteCommand({...base,cwd:"C:/other"})).toThrow("未知");expect(()=>parseRemoteCommand({...base,effort:"unlimited"})).toThrow("参数");expect(parseRemoteCommand({...base,modelId:undefined,effort:"auto"}).effort).toBe("auto")});
 it("routes original service mutations with device identity and validates their inputs",async()=>{const controller={pauseAutomation:vi.fn(async()=>[]),switchAccount:vi.fn(),remoteOptions:vi.fn(async()=>({workspaces:[]}))};const service=new RemoteWorkbenchService(controller as unknown as AppController,await root());await service.mutate({kind:"automation.pause",target:"task",data:{paused:true}},"device","op");expect(controller.pauseAutomation).toHaveBeenCalledWith("task",true);await expect(service.mutate({kind:"automation.pause",target:"task",data:{paused:"true"}},"device","op2")).rejects.toThrow("参数");expect(controller.pauseAutomation).toHaveBeenCalledTimes(1)});
 it("does not report a saved but unregistered task as successful",async()=>{const controller={remoteOptions:vi.fn(async()=>({workspaces:[{id:"project",path:"C:/demo"}]})),createRemoteAutomation:vi.fn(async()=>({id:"new-task",registrationStatus:"error",registrationError:"scheduler unavailable"}))};const service=new RemoteWorkbenchService(controller as unknown as AppController,await root());await expect(service.mutate({kind:"automation.create",data:{workspaceId:"project",input:{name:"one"}}},"device","op")).rejects.toMatchObject({resultSessionId:"new-task",message:expect.stringContaining("未注册")});expect(controller.createRemoteAutomation).toHaveBeenCalledWith(expect.objectContaining({workspace:"C:/demo"}),undefined)});
 it("passes revision into the original task transaction and resolves only known workspaces",async()=>{const controller={listAutomations:vi.fn(async()=>[{id:"task",revision:3}]),remoteOptions:vi.fn(async()=>({workspaces:[{id:"project",path:"C:/demo"}]})),updateAutomation:vi.fn(async()=>[{id:"task",registrationStatus:"registered"}])};const service=new RemoteWorkbenchService(controller as unknown as AppController,await root());await service.mutate({kind:"automation.update",target:"task",data:{revision:3,workspaceId:"project",patch:{name:"edit"}}},"device","op");expect(controller.updateAutomation).toHaveBeenCalledWith("task",{name:"edit",workspace:"C:/demo"},3);await expect(service.mutate({kind:"automation.update",target:"task",data:{revision:2,patch:{name:"old"}}},"device","op2")).rejects.toThrow("其他端");expect(controller.updateAutomation).toHaveBeenCalledTimes(1)});
});
describe("remote context policy",()=>{
 it("uses the native owner and rejects busy or read-only targets",async()=>{const controller={remoteSessions:vi.fn(async()=>[{id:"s",canSend:true}]),remoteSnapshot:vi.fn(async()=>({runtime:{mutable:true}})),setSessionCompactionPolicy:vi.fn(async()=>({}))};const service=new RemoteWorkbenchService(controller as unknown as AppController,await root());await service.mutate({kind:"session.compaction",target:"s",data:{mode:"custom",thresholdPercent:75}},"device","op");expect(controller.setSessionCompactionPolicy).toHaveBeenCalledWith("s",{mode:"custom",thresholdPercent:75});controller.remoteSnapshot.mockResolvedValue({runtime:{mutable:false,reason:"busy"}}as any);await expect(service.mutate({kind:"session.compaction",target:"s",data:{mode:"inherit"}},"device","op2")).rejects.toThrow("busy");await expect(service.mutate({kind:"session.compaction",target:"s",data:{mode:"custom",thresholdPercent:100}},"device","op3")).rejects.toThrow("参数");expect(controller.setSessionCompactionPolicy).toHaveBeenCalledTimes(1)})
});
describe("durable attachment transfer",()=>{
 it("resumes exact chunk offsets and binds completion to device and session",async()=>{const files=new RemoteFiles(await root());const known=vi.fn(async()=>undefined);const created=await files.upload({name:"notes.txt",size:6,mimeType:"text/plain",sessionId:"session"},"device",known)as{id:string};expect(known).toHaveBeenCalledWith("session");await files.upload({id:created.id,offset:0,data:Buffer.from("abc").toString("base64")},"device",known);await expect(files.attachments([created.id],"device","session")).rejects.toThrow("未上传完成");expect(await files.upload({id:created.id},"device",known)).toMatchObject({offset:3});await files.upload({id:created.id,offset:3,data:Buffer.from("def").toString("base64")},"device",known);const [attachment]=await files.attachments([created.id],"device","session");expect(await readFile(attachment!.path!,"utf8")).toBe("abcdef");await expect(files.attachments([created.id],"other","session")).rejects.toThrow("设备");await expect(files.attachments([created.id],"device","other-session")).rejects.toThrow("会话")});
 it("never grows a file on repeated chunks and rejects forward gaps",async()=>{const files=new RemoteFiles(await root()),known=async()=>undefined;const created=await files.upload({name:"a.txt",size:6,sessionId:"session"},"device",known)as{id:string};const chunk={id:created.id,offset:0,data:Buffer.from("abc").toString("base64")};await files.upload(chunk,"device",known);expect(await files.upload(chunk,"device",known)).toMatchObject({offset:3});await expect(files.upload({id:created.id,offset:5,data:Buffer.from("x").toString("base64")},"device",known)).rejects.toThrow("进度");expect(await files.upload({id:created.id},"device",known)).toMatchObject({offset:3})});
});

describe("media handles and transfer tickets",()=>{
 it("opens an actual registered unscoped handle and binds the ticket to its stored owner",async()=>{
   const base=await root(),folder=join(base,"session-media",sessionCacheKey("image-s"));await mkdir(folder,{recursive:true});
   const path=join(folder,"picture.png"),bytes=Buffer.from("actual-cache-file");await writeFile(path,bytes);
   const access=new MediaAccessService(base),handle=await access.register("image-s",path,"image","image/png");
   const controller={listCodeImages:async()=>[handle],remoteSessions:async()=>[],listImageWorkspace:async()=>({conversations:[{id:"image-s"}]}),resolveRemoteMediaRequest:async(source:string)=>{const record=await access.resolve(source);return {...record,size:bytes.length}}};
   const service=new RemoteWorkbenchService(controller as unknown as AppController,base);
   expect((await service.query(new URLSearchParams({kind:"code-images"}),"device")as any[])[0].source).toBe(handle.url);
   for(const source of [handle.url,handle.url+"?variant=thumbnail"]){const result=await service.query(new URLSearchParams({kind:"media",source}),"device")as any;expect(result).toMatchObject({sessionId:"image-s",mimeType:"image/png",size:bytes.length});const chunk=await service.query(new URLSearchParams({kind:"asset-chunk",ticket:result.ticket}),"device")as any;expect(Buffer.from(chunk.data,"base64")).toEqual(bytes);await expect(service.query(new URLSearchParams({kind:"asset-chunk",ticket:result.ticket}),"other")).rejects.toThrow("过期")}
   await access.removeSession("image-s");await expect(service.query(new URLSearchParams({kind:"media",source:handle.url}),"device")).rejects.toThrow("失效");
 });
});
