import{describe,it,expect,vi,afterEach}from"vitest";
import{mkdtemp,writeFile,readFile,rm}from"node:fs/promises";
import{tmpdir}from"node:os";import{join}from"node:path";import{generateKeyPairSync}from"node:crypto";
import{RemotePushService}from"./remote-push-service";
const roots:string[]=[];afterEach(async()=>{for(const root of roots.splice(0))await rm(root,{recursive:true,force:true})});
describe("optional remote push",()=>{
 it("stays inactive without configuration and never reads task content",async()=>{const root=await mkdtemp(join(tmpdir(),"grok-push-"));roots.push(root);const read=vi.fn(async()=>[]),request=vi.fn();const service=new RemotePushService(root,{encrypt:s=>s,decrypt:s=>s},request);expect((await service.status()).configured).toBe(false);await service.poll(read,"computer",["device"]);expect(read).not.toHaveBeenCalled();expect(request).not.toHaveBeenCalled()});
 it("encrypts credentials/tokens and sends only generic notices and original identities",async()=>{
  const root=await mkdtemp(join(tmpdir(),"grok-push-"));roots.push(root);const {privateKey}=generateKeyPairSync("rsa",{modulusLength:2048,privateKeyEncoding:{type:"pkcs8",format:"pem"},publicKeyEncoding:{type:"spki",format:"pem"}});const credential=join(root,"credential.json"),android=join(root,"android.json");await writeFile(credential,JSON.stringify({project_id:"fixture-project",client_email:"fixture@example.invalid",private_key:privateKey}));await writeFile(android,JSON.stringify({project_info:{project_id:"fixture-project",project_number:"123"},client:[{client_info:{mobilesdk_app_id:"fixture-app",android_client_info:{package_name:"io.github.grokbuilddesktop.companion"}},api_key:[{current_key:"fixture-api-key"}]}]}));
  const request=vi.fn(async(url:string)=>new Response(JSON.stringify(url.includes("oauth2")?{access_token:"fixture-access",expires_in:3600}:{name:"fixture-message"}),{status:200}));const service=new RemotePushService(root,{encrypt:s=>Buffer.from(s).toString("base64"),decrypt:s=>Buffer.from(s,"base64").toString()},request);await service.configure(credential,android);await service.register("device","fixture-push-token",2);const stored=await readFile(join(root,"remote","push.json"),"utf8");expect(stored).not.toContain("PRIVATE KEY");expect(stored).not.toContain("fixture-push-token");expect((await service.status("device")).registered).toBe(true);
  await service.poll(async()=>[],"computer",["device"]);await service.poll(async()=>[{id:"notice-one",kind:"completion",title:"private-title-not-for-push",detail:"private-content-not-for-push",sessionId:"original-session",read:false,createdAt:new Date().toISOString()}],"computer",["device"]);expect(request).toHaveBeenCalledTimes(2);const body=String((request.mock.calls[1] as unknown as [string,RequestInit])[1].body);expect(body).not.toContain("private-title");expect(body).not.toContain("private-content");expect(JSON.parse(body).message.data).toEqual({computer:"computer",sessionId:"original-session",kind:"completion",noticeId:"notice-one"});expect(JSON.parse(body).message.notification).toBeUndefined();await service.poll(async()=>[{id:"notice-one",kind:"completion",title:"x",read:false,createdAt:""}],"computer",["device"]);expect(request).toHaveBeenCalledTimes(2);
  await service.register("device","fixture-push-token");
  await service.poll(async()=>[{id:"legacy-event",kind:"failure",title:"private-title",read:false,createdAt:""}],"computer",["device"]);
  const legacy=JSON.parse(String((request.mock.calls.at(-1) as unknown as [string,RequestInit])[1].body)).message;
  expect(legacy.notification.title).toContain("失败");expect(legacy.android.notification.channel_id).toBe("grok-failed");expect(legacy.android.notification.tag).toBe("legacy-event");
 });
});
