import { afterEach,describe,expect,it,vi } from "vitest";
import { mkdtemp,readFile,rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { request } from "node:https";
import { createServer } from "node:net";
import { X509Certificate } from "node:crypto";
import { RemoteGatewayService,type RemoteBackend,parseRemoteCommand } from "./remote-gateway-service";
const stamp=Date.now();
const op=(name:string)=>`${stamp}_${name}`;
const cleanup:Array<()=>Promise<void>>=[];
afterEach(async()=>{for(const dispose of cleanup.splice(0).reverse())await dispose()});
async function setup(perform:RemoteBackend["perform"]=async()=>({state:"completed"})){const root=await mkdtemp(join(tmpdir(),"grok-remote-test-"));const backend:RemoteBackend={sessions:vi.fn(async()=>[{id:"session-one",cwd:"C:/demo",projectName:"demo",title:"Known session",updatedAt:"",status:"idle" as const,canSend:true}]),snapshot:vi.fn(async (id:string)=>({session:{id,cwd:"C:/demo",projectName:"demo",title:"Known session",updatedAt:"",status:"idle" as const,canSend:true},events:[],totalEvents:0,truncated:false,pending:[]})),perform:vi.fn(perform)};const service=new RemoteGatewayService(root,backend,{encrypt:value=>Buffer.from(value).toString("base64"),decrypt:value=>Buffer.from(value,"base64").toString()});cleanup.push(async()=>{await service.dispose();await rm(root,{recursive:true,force:true})});const reserve=createServer();await new Promise<void>(r=>reserve.listen(0,"127.0.0.1",r));const port=(reserve.address() as {port:number}).port;await new Promise<void>(r=>reserve.close(()=>r()));await service.setEnabled(true,port);const persisted=JSON.parse(await readFile(join(root,"remote","gateway.json"),"utf8"));const state=await service.state();
 const call=(path:string,body?:unknown,token="",pin=state.fingerprint!)=>new Promise<{status:number;body:any}>((resolve,reject)=>{const req=request({hostname:"127.0.0.1",port,path,method:body===undefined?"GET":"POST",ca:persisted.certificate,checkServerIdentity:(_,cert)=>new X509Certificate(cert.raw).fingerprint256.replaceAll(":","").toLowerCase()===pin?undefined:Error("fingerprint mismatch"),headers:{...(token?{Authorization:`Bearer ${token}`}:{})}},res=>{let raw="";res.on("data",d=>raw+=d);res.on("end",()=>resolve({status:res.statusCode!,body:JSON.parse(raw)}))});req.on("error",reject);req.end(body===undefined?undefined:JSON.stringify(body))});
 const pair=async()=>{const offer=await service.beginPairing();const response=await call("/v1/pair",{code:offer.pairing!.code,name:"Android test"});await service.decidePair(response.body.requestId,true);return (await call("/v1/pair/status",{requestId:response.body.requestId,code:offer.pairing!.code})).body.deviceToken as string};return {root,service,backend,call,pair,port};}
describe("paired remote gateway",()=>{
 it("requires pinned TLS, explicit Desktop pairing consent and revocable device auth",async()=>{const t=await setup();expect((await t.call("/v1/sessions")).status).toBe(401);await expect(t.call("/v1/info",undefined,"","a".repeat(64))).rejects.toThrow("fingerprint");const offer=await t.service.beginPairing();const pending=await t.call("/v1/pair",{code:offer.pairing!.code,name:"my phone"});expect((await t.call("/v1/pair/status",{requestId:pending.body.requestId,code:offer.pairing!.code})).body).not.toHaveProperty("deviceToken");await t.service.decidePair(pending.body.requestId,true);const approved=await t.call("/v1/pair/status",{requestId:pending.body.requestId,code:offer.pairing!.code});const token=approved.body.deviceToken;expect((await t.call("/v1/sessions",undefined,token)).body.sessions).toHaveLength(1);await t.service.revoke(approved.body.deviceId);expect((await t.call("/v1/sessions",undefined,token)).status).toBe(401)});
 it("returns a durable receipt without waiting for the model and dispatches duplicate IDs once",async()=>{let finish!:(v:any)=>void;const t=await setup(()=>new Promise(resolve=>finish=resolve));const token=await t.pair();const command={operationId:op("operation-one"),sessionId:"session-one",action:"send",text:"hello"};const results=await Promise.all([t.call("/v1/operations",command,token),t.call("/v1/operations",command,token)]);expect(results.map(r=>r.status)).toEqual([202,202]);expect(t.backend.perform).toHaveBeenCalledTimes(1);expect((await t.call(`/v1/operations/${op("operation-one")}`,undefined,token)).body.state).toBe("accepted");expect((await t.call("/v1/operations",{...command,text:"different"},token)).status).toBe(400);finish({state:"completed"});await vi.waitFor(async()=>expect((await t.call(`/v1/operations/${op("operation-one")}`,undefined,token)).body.state).toBe("completed"));const persisted=await readFile(join(t.root,"remote","gateway.json"),"utf8");expect(persisted).not.toContain('"text":"hello"')});
 it("keeps queued receipts and records backend failure rather than claiming successful execution",async()=>{const t=await setup(async command=>{if(command.text==="fail")throw Error("model offline");return {state:"queued"}});const token=await t.pair();await t.call("/v1/operations",{operationId:op("queue-one"),sessionId:"session-one",action:"send",text:"queued"},token);await vi.waitFor(async()=>expect((await t.call(`/v1/operations/${op("queue-one")}`,undefined,token)).body.state).toBe("queued"));await t.call("/v1/operations",{operationId:op("fail-one"),sessionId:"session-one",action:"send",text:"fail"},token);await vi.waitFor(async()=>expect((await t.call(`/v1/operations/${op("fail-one")}`,undefined,token)).body).toMatchObject({state:"failed",message:"model offline"}))});
 it("recovers pending operations as unknown after restart and never resubmits them",async()=>{const t=await setup(()=>new Promise(()=>{}));const token=await t.pair();await t.call("/v1/operations",{operationId:op("restart-one"),sessionId:"session-one",action:"send",text:"once"},token);await t.service.dispose();const restarted=new RemoteGatewayService(t.root,t.backend,{encrypt:s=>Buffer.from(s).toString("base64"),decrypt:s=>Buffer.from(s,"base64").toString()});cleanup.push(()=>restarted.dispose());await restarted.state();const store=JSON.parse(await readFile(join(t.root,"remote","gateway.json"),"utf8"));expect(store.operations[0].state).toBe("unknown");expect(t.backend.perform).toHaveBeenCalledTimes(1)});
 it("reads histories without dispatching execution and validates pagination",async()=>{const t=await setup();const token=await t.pair();expect((await t.call("/v1/sessions/session-one?before=12",undefined,token)).status).toBe(200);expect(t.backend.snapshot).toHaveBeenCalledWith("session-one",12,undefined);expect(t.backend.perform).not.toHaveBeenCalled();expect((await t.call("/v1/sessions/session-one?before=-1",undefined,token)).status).toBe(400)});
 it("rejects invalid actions, unknown fields and malformed answers",()=>{expect(()=>parseRemoteCommand({operationId:op("valid"),sessionId:"b",action:"shell",text:"whoami"})).toThrow();expect(()=>parseRemoteCommand({operationId:op("valid"),sessionId:"b",action:"send",text:"ok",alwaysApprove:true})).toThrow();expect(()=>parseRemoteCommand({operationId:op("valid"),sessionId:"b",action:"question",requestId:"q",answers:{x:123}})).toThrow()});
 it("creates once through a receipt, returns its actual identity and scopes metadata fields",async()=>{const t=await setup(async()=>({state:"completed",resultSessionId:"created-session"}));t.backend.options=async()=>({capabilities:["session.create"],workspaces:[]});const token=await t.pair();expect((await t.call("/v1/options",undefined,token)).body.capabilities).toContain("session.create");const command={operationId:op("create-once"),sessionId:"new",action:"create",workspaceId:"known-project"};await t.call("/v1/operations",command,token);await t.call("/v1/operations",command,token);await vi.waitFor(async()=>expect((await t.call(`/v1/operations/${command.operationId}`,undefined,token)).body).toMatchObject({state:"completed",resultSessionId:"created-session"}));expect(t.backend.perform).toHaveBeenCalledTimes(1);expect(()=>parseRemoteCommand({...command,archived:true})).toThrow("未知");expect(()=>parseRemoteCommand({...command,action:"archive",workspaceId:undefined,archived:"true"})).toThrow();expect(parseRemoteCommand({operationId:op("rename"),sessionId:"known",action:"rename",title:" New name "}).title).toBe("New name");});
});
