import {afterEach,expect,it} from "vitest";
import {mkdtemp,rm,writeFile,mkdir} from "node:fs/promises";
import {tmpdir} from "node:os";
import {join} from "node:path";
import {zipSync,strToU8} from "fflate";
import {readWorkspaceArtifact} from "./workspace-artifact-service";
const roots:string[]=[];
afterEach(async()=>{await Promise.all(roots.splice(0).map(root=>rm(root,{recursive:true,force:true}))) });
async function fixture(){const root=await mkdtemp(join(tmpdir(),"grok-artifact-"));roots.push(root);const workspace=join(root,"workspace");await mkdir(workspace);return {root,workspace}}
it("reads original text, media and static HTML without interpreting markup",async()=>{const {workspace}=await fixture();for(const [name,data,kind] of [["note.md","# 中文","text"],["page.html","<script>danger()</script>","html"],["picture.png","binary","image"]]){const path=join(workspace,name!);await writeFile(path,data!);const result=await readWorkspaceArtifact(workspace,path);expect(result.kind).toBe(kind);expect(result.data).toBe(kind==="image"?Buffer.from(data!).toString("base64"):data)}});
it("decodes UTF-16 text with either byte order mark",async()=>{const {workspace}=await fixture();const little=Buffer.from("测试文本","utf16le");const big=Buffer.from(little);for(let i=0;i<big.length;i+=2)[big[i],big[i+1]]=[big[i+1]!,big[i]!];for(const [name,bom,body] of [["little.txt",[0xff,0xfe],little],["big.txt",[0xfe,0xff],big]] as const){const path=join(workspace,name);await writeFile(path,Buffer.concat([Buffer.from(bom),body]));expect((await readWorkspaceArtifact(workspace,path)).data).toBe("测试文本")}});
it("rejects escaped paths, unsupported files and large content",async()=>{const {root,workspace}=await fixture();const outside=join(root,"secret.txt");await writeFile(outside,"private");await expect(readWorkspaceArtifact(workspace,outside)).rejects.toThrow("不属于");const unsupported=join(workspace,"binary.exe");await writeFile(unsupported,"x");await expect(readWorkspaceArtifact(workspace,unsupported)).rejects.toThrow("格式");const large=join(workspace,"huge.md");await writeFile(large,"x".repeat(2*1024*1024+1));await expect(readWorkspaceArtifact(workspace,large)).rejects.toThrow("上限")});
it("extracts bounded Office content and rejects inflated document bodies",async()=>{const {workspace}=await fixture();const path=join(workspace,"sample.docx");await writeFile(path,zipSync({"word/document.xml":strToU8("<w:p><w:t>Hello &amp; 中文</w:t></w:p>"),"word/embedded.bin":strToU8("not displayed")}));const result=await readWorkspaceArtifact(workspace,path);expect(result.kind).toBe("office");expect(result.data).toContain("Hello & 中文");expect(result.data).not.toContain("not displayed");await writeFile(path,zipSync({"word/document.xml":strToU8("x".repeat(8*1024*1024+1))}));await expect(readWorkspaceArtifact(workspace,path)).rejects.toThrow("展开内容过大")});
