import {afterEach,expect,it} from "vitest";
import {mkdtemp,rm,writeFile,mkdir} from "node:fs/promises";
import {tmpdir} from "node:os";
import {join} from "node:path";
import {zipSync,strToU8} from "fflate";
import {readWorkspaceArtifact} from "./workspace-artifact-service";
import {rememberCanonicalPath} from "./renderer-path-policy";
const roots:string[]=[];
afterEach(async()=>{await Promise.all(roots.splice(0).map(root=>rm(root,{recursive:true,force:true}))) });
async function fixture(){const root=await mkdtemp(join(tmpdir(),"grok-artifact-"));roots.push(root);const workspace=join(root,"workspace");await mkdir(workspace);return {root,workspace}}
it("reads original text, media and static HTML without interpreting markup",async()=>{const {workspace}=await fixture();for(const [name,data,kind] of [["note.md","# 中文","text"],["page.html","<script>danger()</script>","html"],["picture.png","binary","image"]]){const path=join(workspace,name!);await writeFile(path,data!);const result=await readWorkspaceArtifact(workspace,path);expect(result.kind).toBe(kind);expect(result.data).toBe(kind==="image"?Buffer.from(data!).toString("base64"):data)}});
it("decodes UTF-16 text with either byte order mark",async()=>{const {workspace}=await fixture();const little=Buffer.from("测试文本","utf16le");const big=Buffer.from(little);for(let i=0;i<big.length;i+=2)[big[i],big[i+1]]=[big[i+1]!,big[i]!];for(const [name,bom,body] of [["little.txt",[0xff,0xfe],little],["big.txt",[0xfe,0xff],big]] as const){const path=join(workspace,name);await writeFile(path,Buffer.concat([Buffer.from(bom),body]));expect((await readWorkspaceArtifact(workspace,path)).data).toBe("测试文本")}});
it("rejects escaped paths, unsupported files and large content",async()=>{const {root,workspace}=await fixture();const outside=join(root,"secret.txt");await writeFile(outside,"private");await expect(readWorkspaceArtifact(workspace,outside)).rejects.toThrow("不属于");const unsupported=join(workspace,"binary.exe");await writeFile(unsupported,"x");await expect(readWorkspaceArtifact(workspace,unsupported)).rejects.toThrow("格式");const large=join(workspace,"huge.md");await writeFile(large,"x".repeat(2*1024*1024+1));await expect(readWorkspaceArtifact(workspace,large)).rejects.toThrow("上限")});
it("extracts bounded Office content and rejects inflated document bodies",async()=>{const {workspace}=await fixture();const path=join(workspace,"sample.docx");await writeFile(path,zipSync({"word/document.xml":strToU8("<w:p><w:t>Hello &amp; 中文</w:t></w:p>"),"word/embedded.bin":strToU8("not displayed")}));const result=await readWorkspaceArtifact(workspace,path);expect(result.kind).toBe("office");expect(result.data).toContain("Hello & 中文");expect(result.data).not.toContain("not displayed");await writeFile(path,zipSync({"word/document.xml":strToU8("x".repeat(8*1024*1024+1))}));await expect(readWorkspaceArtifact(workspace,path)).rejects.toThrow("展开内容过大")});
it("previews common developer extensions that are safe as plain text",async()=>{const {workspace}=await fixture();for(const name of ["cli.mjs","legacy.cjs","types.mts","types.cts","theme.scss","theme.sass","theme.less","Card.vue","Card.svelte","page.astro","app.ini","nginx.conf","service.cfg","gradle.properties","local.env","yarn.lock","main.rb","index.php","App.kt","build.gradle.kts","Model.swift","Program.cs","lib.lua","analysis.r","script.pl","task.ex","task.exs","module.erl","Main.scala","core.clj","schema.proto","api.graphql","api.gql","schema.prisma","main.tf","app.hcl","Build.gradle","CMakeLists.cmake","run.bat","run.cmd","module.psm1","manifest.psd1","setup.zsh","config.fish","script.bash","scan.awk","edit.sed","change.diff","fix.patch","table.tsv","events.ndjson","events.jsonl","tsconfig.json5","paper.tex","doc.rst","doc.adoc","notes.org"]){const path=join(workspace,name);await writeFile(path,"plain text");const result=await readWorkspaceArtifact(workspace,path);expect([result.kind,result.data],name).toEqual(["text","plain text"])}});
it("previews extensionless and dotfile project files by basename",async()=>{const {workspace}=await fixture();for(const [name,expected] of [["Dockerfile","FROM node:20"],["Makefile","all:"],[".gitignore","node_modules"],[".env","TOKEN=1"],[".editorconfig","root = true"],["LICENSE","MIT"],["README","# Title"],[".npmrc","strict=true"],["Procfile","web: node ."],["Gemfile","source 'x'"],["Rakefile","task :default"],["run","echo hi"]] as const){const path=join(workspace,name);await writeFile(path,expected);const result=await readWorkspaceArtifact(workspace,path);expect([result.kind,result.data],name).toEqual(["text",expected])}const unknown=join(workspace,"binary.exe");await writeFile(unknown,"MZ");await expect(readWorkspaceArtifact(workspace,unknown)).rejects.toThrow("格式")});
it("refuses binary content even when the name looks like text",async()=>{const {workspace}=await fixture();const path=join(workspace,"renamed.txt");await writeFile(path,Buffer.from([0x50,0x4b,0x03,0x04,0x00,0x01,0x02]));await expect(readWorkspaceArtifact(workspace,path)).rejects.toThrow("不是文本");const utf16=join(workspace,"wide.txt");await writeFile(utf16,Buffer.concat([Buffer.from([0xff,0xfe]),Buffer.from("测试文本","utf16le")]));expect((await readWorkspaceArtifact(workspace,utf16)).data).toBe("测试文本")});
it("keeps the inline-asset budget for HTML while text stays at 2 MB",async()=>{const {workspace}=await fixture();const html=join(workspace,"report.html");await writeFile(html,Buffer.alloc(3*1024*1024,"<"));expect((await readWorkspaceArtifact(workspace,html)).data.length).toBe(3*1024*1024);const huge=join(workspace,"huge.html");await writeFile(huge,Buffer.alloc(20*1024*1024+1,"<"));await expect(readWorkspaceArtifact(workspace,huge)).rejects.toThrow("上限");const big=join(workspace,"big.md");await writeFile(big,Buffer.alloc(2*1024*1024+1,"x"));await expect(readWorkspaceArtifact(workspace,big)).rejects.toThrow("上限")});
it("still refuses traversal and out-of-workspace reads unless a picker issued the path",async()=>{const {root,workspace}=await fixture();const outside=join(root,"secret.txt");await writeFile(outside,"private");await expect(readWorkspaceArtifact(workspace,join(workspace,"..","secret.txt"))).rejects.toThrow("不属于");const issued=new Set<string>();rememberCanonicalPath(issued,outside);const picked=await readWorkspaceArtifact(workspace,outside,{issuedPaths:issued});expect(picked.data).toBe("private");const sibling=join(root,"other.txt");await writeFile(sibling,"other");await expect(readWorkspaceArtifact(workspace,sibling,{issuedPaths:issued})).rejects.toThrow("不属于")});
