import {browserAddress} from "../../../shared/browser-address";
import {UiIcon} from "../ui-icons";
import {useEffect,useRef,useState} from "react";
import type {WorkspaceBrowserTab,PreviewServer} from "../../../shared/workspace-tools";
import type {GrokDesktopApi} from "../../../shared/types";
import {useWorkbenchStore} from "../workbench-store";
import {useAppStore} from "../store";
import {UiDialog} from "./ui/primitives";
export function BrowserWorkbench({onError}:{onError(message:string):void}) {
 const selectedId=useWorkbenchStore(state=>state.activeBrowserId);
 const workspace=useAppStore(state=>state.settings?.activeWorkspace||"");
 const sessionId=useAppStore(state=>state.activeSessionId);
 const [tabs,setTabs]=useState<WorkspaceBrowserTab[]>([]),[active,setActive]=useState(readActiveBrowser),[address,setAddress]=useState("");
 const [busy,setBusy]=useState(false),[scripts,setScripts]=useState<string[]>([]),[script,setScript]=useState(""),[servers,setServers]=useState<PreviewServer[]>([]);
 const [feedback,setFeedback]=useState<Awaited<ReturnType<GrokDesktopApi["captureBrowserFeedback"]>>>(),[comment,setComment]=useState("");
 const [region,setRegion]=useState<{x:number;y:number;width:number;height:number}>();const anchor=useRef<{x:number;y:number}|undefined>(undefined);
 const activeRef=useRef(active);const tab=tabs.find(tab=>tab.id===active);
 const select=(id:string)=>{activeRef.current=id;setActive(id);useWorkbenchStore.getState().setActiveBrowser(id);try{localStorage.setItem("grok.active-browser.v1",id)}catch{}};
 const perform=async(run:()=>Promise<unknown>)=>{setBusy(true);try{await run()}catch(error){onError(String(error))}finally{setBusy(false)}};
 useEffect(()=>{let disposed=false;const apply=(rows:WorkspaceBrowserTab[])=>{if(disposed)return;setTabs(rows);if(!rows.some(row=>row.id===activeRef.current))select(rows[0]?.id||"")};const off=window.grokDesktop.onWorkspaceBrowser(apply);void window.grokDesktop.listWorkspaceBrowserTabs().then(apply).catch(error=>onError(String(error)));return()=>{disposed=true;off()}},[]);
 useEffect(()=>{if(selectedId&&tabs.some(row=>row.id===selectedId)){activeRef.current=selectedId;setActive(selectedId)}},[selectedId,tabs]);
 useEffect(()=>{setAddress(tab?.url==="about:blank"?"":tab?.url||"")},[tab?.id,tab?.url]);
 useEffect(()=>{let disposed=false;setScripts([]);setServers([]);if(!workspace)return;void window.grokDesktop.previewConfigurations(workspace).then(values=>{if(!disposed){setScripts(values);setScript(values[0]||"")}}).catch(error=>onError(String(error)));const refresh=()=>void window.grokDesktop.listPreviewServers(workspace).then(rows=>{if(!disposed)setServers(rows)}).catch(()=>undefined);refresh();const timer=setInterval(refresh,2500);return()=>{disposed=true;clearInterval(timer)}},[workspace]);
 const create=async(url="about:blank")=>{const created=await window.grokDesktop.createWorkspaceBrowserTab(url,{workspace:workspace||undefined,sessionId:sessionId||undefined});setTabs(rows=>rows.some(row=>row.id===created.id)?rows:[...rows,created]);select(created.id)};
 const navigate=async()=>{if(tab&&address.trim())await window.grokDesktop.navigateWorkspaceBrowser(tab.id,browserAddress(address.trim()))};
 const command=(action:"back"|"forward"|"reload"|"stop")=>{if(tab)void perform(()=>window.grokDesktop.commandWorkspaceBrowser(tab.id,action))};
 const annotate=()=>void perform(async()=>{if(!tab)return;const surface=document.querySelector<HTMLElement>(".browser-surface");if(!surface)throw Error("网页视图尚未就绪");const rect=surface.getBoundingClientRect();if(rect.width<10||rect.height<10)throw Error("网页视图没有可截图的区域");await window.grokDesktop.boundsWorkspaceBrowser(tab.id,{x:rect.x,y:rect.y,width:rect.width,height:rect.height,visible:true});await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));setFeedback(await window.grokDesktop.captureBrowserFeedback(tab.id));setComment("");setRegion(undefined)});
 const point=(event:React.PointerEvent<HTMLDivElement>)=>{const box=event.currentTarget.getBoundingClientRect();return {x:Math.max(0,Math.min(1,(event.clientX-box.left)/box.width)),y:Math.max(0,Math.min(1,(event.clientY-box.top)/box.height))}};
 return <section className="browser-workbench"><header><div><h2>网页预览</h2><small>{tab?.sessionId?`关联会话 ${tab.sessionId.slice(0,8)}`:"手动预览 · 反馈加入当前会话草稿"} · 模型浏览器工具尚未连接</small></div><button disabled={busy} onClick={()=>void perform(()=>create())}>新标签</button></header>
 <div className="preview-server-bar">{scripts.length>0?<><select aria-label="开发服务器脚本" value={script} onChange={event=>setScript(event.target.value)}>{scripts.map(script=><option key={script} value={script}>npm run {script}</option>)}</select><button disabled={busy||!script||servers.some(server=>server.script===script&&server.status==="running")} onClick={()=>void perform(async()=>{await window.grokDesktop.startPreviewServer(workspace,script);setServers(await window.grokDesktop.listPreviewServers(workspace))})}>启动开发服务器</button></>:<small>可输入已有服务器地址；项目 dev/start/preview 脚本会显示在这里。</small>}
 {servers.map(server=><span key={server.terminalId}>{server.script} · {server.status==="running"?server.url||"等待服务器地址":"已退出"}{server.url&&<button onClick={()=>void perform(()=>create(server.url))}>打开预览</button>}{server.status==="running"&&<button onClick={()=>void perform(async()=>{await window.grokDesktop.stopPreviewServer(server.terminalId);setServers(await window.grokDesktop.listPreviewServers(workspace))})}>停止服务器</button>}</span>)}</div>
 <nav aria-label="浏览器标签">{tabs.map(row=><div key={row.id}><button className={active===row.id?"active":""} title={row.url} onClick={()=>select(row.id)}>{row.loading?"正在加载…":row.title}</button><button aria-label={`关闭 ${row.title}`} onClick={()=>void perform(()=>window.grokDesktop.closeWorkspaceBrowserTab(row.id))}><UiIcon name="close"/></button></div>)}</nav>
 {tab?<><form className="browser-address" onSubmit={event=>{event.preventDefault();void perform(navigate)}}><button type="button" disabled={!tab.canGoBack} aria-label="后退" onClick={()=>command("back")}><UiIcon name="chevron-left"/></button><button type="button" disabled={!tab.canGoForward} aria-label="前进" onClick={()=>command("forward")}><UiIcon name="chevron-right"/></button><button type="button" aria-label={tab.loading?"停止加载":"刷新"} onClick={()=>command(tab.loading?"stop":"reload")}><UiIcon name={tab.loading?"close":"refresh"}/></button><input aria-label="网页地址" placeholder="localhost:3000 或 https://example.com" value={address} onChange={event=>setAddress(event.target.value)}/><button type="submit">打开</button><button type="button" disabled={busy||!/^https?:/.test(tab.url)} onClick={annotate}>截图与区域反馈</button><button type="button" disabled={busy||!/^https?:/.test(tab.url)} onClick={()=>void perform(()=>window.grokDesktop.clearWorkspaceBrowserSite(tab.id))}>清理站点数据</button></form>{tab.downloadStatus&&<p role="status">{tab.downloadStatus}</p>}{tab.error&&<p role="alert">{tab.error}</p>}<BrowserSurface id={tab.id}/></>:<p className="empty-copy">输入开发服务器地址，预览后把截图和问题加入会话，再让 Agent 修复。</p>}
 <UiDialog open={Boolean(feedback)} onOpenChange={open=>{if(!open)setFeedback(undefined)}} title="网页视觉反馈">
 {feedback&&<><p>在截图上拖动框选问题区域，说明需要修复的内容；加入草稿后由你发送。</p><div style={{position:"relative",maxHeight:420,overflow:"auto"}} onPointerDown={event=>{anchor.current=point(event);event.currentTarget.setPointerCapture(event.pointerId)}} onPointerUp={event=>{if(!anchor.current)return;const end=point(event),start=anchor.current;anchor.current=undefined;setRegion({x:Math.min(start.x,end.x),y:Math.min(start.y,end.y),width:Math.abs(start.x-end.x),height:Math.abs(start.y-end.y)})}}><img style={{display:"block",width:"100%",pointerEvents:"none"}} src={feedback.previewUrl} alt="当前网页截图"/>{region&&<div style={{position:"absolute",pointerEvents:"none",border:"2px solid var(--color-accent)",background:"#4488ff22",left:`${region.x*100}%`,top:`${region.y*100}%`,width:`${region.width*100}%`,height:`${region.height*100}%`}}/>}</div><textarea aria-label="网页反馈" value={comment} onChange={event=>setComment(event.target.value)} placeholder="例如：这个按钮被遮住，请修复后刷新验证"/><button disabled={!comment.trim()} onClick={()=>{window.dispatchEvent(new CustomEvent("grok:compose-feedback",{detail:{sessionId:feedback.tab.sessionId,cwd:feedback.tab.workspace,attachments:[feedback.attachment],text:`网页反馈：${feedback.tab.url}\n${region?`问题区域（截图比例）：x=${region.x.toFixed(3)}, y=${region.y.toFixed(3)}, 宽=${region.width.toFixed(3)}, 高=${region.height.toFixed(3)}\n`:""}${comment}`}}));setFeedback(undefined)}}>加入会话草稿</button></>}
 </UiDialog></section>;
}
function readActiveBrowser(){try{return localStorage.getItem("grok.active-browser.v1")||""}catch{return ""}}
function BrowserSurface({id}:{id:string}) {
 const host=useRef<HTMLDivElement>(null);
 useEffect(()=>{const element=host.current;if(!element)return;let last="",disposed=false;let frame=0;
 const sync=()=>{cancelAnimationFrame(frame);frame=requestAnimationFrame(()=>{if(disposed)return;const rect=element.getBoundingClientRect();const blocked=Boolean(document.querySelector('.ui-dialog,[role="menu"],.modal-backdrop,.add-palette-backdrop'));const bounds={x:Math.max(0,rect.x),y:Math.max(0,rect.y),width:Math.max(0,rect.width),height:Math.max(0,rect.height),visible:!blocked&&element.getClientRects().length>0};const signature=JSON.stringify(bounds);if(signature===last)return;last=signature;void window.grokDesktop.boundsWorkspaceBrowser(id,bounds).catch(()=>undefined)})};
 const resize=new ResizeObserver(sync);resize.observe(element);const mutations=new MutationObserver(sync);mutations.observe(document.body,{subtree:true,childList:true,attributes:true,attributeFilter:["hidden","class","data-state"]});window.addEventListener("resize",sync);sync();
 return()=>{disposed=true;cancelAnimationFrame(frame);resize.disconnect();mutations.disconnect();window.removeEventListener("resize",sync);void window.grokDesktop.boundsWorkspaceBrowser(id,{x:0,y:0,width:0,height:0,visible:false}).catch(()=>undefined)};
 },[id]);return <div className="browser-surface" ref={host} aria-label="隔离网页内容"/>;
}
