import {browserAddress} from "../../../shared/browser-address";
import {UiIcon} from "../ui-icons";
import {useEffect,useRef,useState} from "react";
import type {WorkspaceBrowserTab} from "../../../shared/workspace-tools";
import {useWorkbenchStore} from "../workbench-store";
export function BrowserWorkbench({onError}:{onError(message:string):void}) {
 const selectedId=useWorkbenchStore(state=>state.activeBrowserId);
 const [tabs,setTabs]=useState<WorkspaceBrowserTab[]>([]);const [active,setActive]=useState(()=>readActiveBrowser());const activeRef=useRef(active);const [address,setAddress]=useState("");const [busy,setBusy]=useState(false);const tab=tabs.find(t=>t.id===active);
 const select=(id:string)=>{activeRef.current=id;setActive(id);useWorkbenchStore.getState().setActiveBrowser(id);try{if(id)localStorage.setItem("grok.active-browser.v1",id)}catch{}};
 useEffect(()=>{let disposed=false;const apply=(rows:WorkspaceBrowserTab[])=>{if(disposed)return;setTabs(rows);const preferred=useWorkbenchStore.getState().activeBrowserId||readActiveBrowser();select(rows.some(row=>row.id===preferred)?preferred:rows.some(row=>row.id===activeRef.current)?activeRef.current:rows[0]?.id||"")};const off=window.grokDesktop.onWorkspaceBrowser(apply);void window.grokDesktop.listWorkspaceBrowserTabs().then(apply).catch(error=>onError(String(error)));return()=>{disposed=true;off()}},[]);
 useEffect(()=>{if(selectedId&&tabs.some(row=>row.id===selectedId)){activeRef.current=selectedId;setActive(selectedId)}},[selectedId,tabs]);
 useEffect(()=>{setAddress(tab?.url==="about:blank"?"":tab?.url||"")},[tab?.id,tab?.url]);
 const create=async()=>{setBusy(true);try{const created=await window.grokDesktop.createWorkspaceBrowserTab("about:blank");setTabs(rows=>rows.some(row=>row.id===created.id)?rows:[...rows,created]);select(created.id)}catch(error){onError(String(error))}finally{setBusy(false)}};
 const navigate=async()=>{if(!tab||!address.trim())return;const input=address.trim();try{await window.grokDesktop.navigateWorkspaceBrowser(tab.id,browserAddress(input))}catch(error){onError(String(error))}};
 const command=(action:"back"|"forward"|"reload"|"stop")=>{if(tab)void window.grokDesktop.commandWorkspaceBrowser(tab.id,action).catch(error=>onError(String(error)))};
 return <section className="browser-workbench"><header><h2>网页预览</h2><small>手动查看本机开发服务器或网站 · 未连接模型浏览器工具</small><button disabled={busy} onClick={()=>void create()}>新标签</button></header><nav aria-label="浏览器标签">{tabs.map(row=><div key={row.id}><button className={active===row.id?"active":""} title={row.url} onClick={()=>select(row.id)}>{row.loading?"正在加载…":row.title}</button><button aria-label={`关闭 ${row.title}`} onClick={()=>void window.grokDesktop.closeWorkspaceBrowserTab(row.id).catch(error=>onError(String(error)))}><UiIcon name="close"/></button></div>)}</nav>{tab?<><form className="browser-address" onSubmit={event=>{event.preventDefault();void navigate()}}><button type="button" disabled={!tab.canGoBack} aria-label="后退" onClick={()=>command("back")}><UiIcon name="chevron-left"/></button><button type="button" disabled={!tab.canGoForward} aria-label="前进" onClick={()=>command("forward")}><UiIcon name="chevron-right"/></button><button type="button" aria-label={tab.loading?"停止加载":"刷新"} onClick={()=>command(tab.loading?"stop":"reload")}><UiIcon name={tab.loading?"close":"refresh"}/></button><input aria-label="网页地址" placeholder="例如 localhost:3000 或 https://example.com" value={address} onChange={event=>setAddress(event.target.value)}/><button type="submit">打开</button><button type="button" disabled={!/^https?:/.test(tab.url)} onClick={()=>void window.grokDesktop.clearWorkspaceBrowserSite(tab.id).catch(error=>onError(String(error)))}>清理当前站点数据</button></form>{tab.downloadStatus&&<p role="status">{tab.downloadStatus}</p>}{tab.error&&<p className="inline-note" role="alert">{tab.error}</p>}<BrowserSurface id={tab.id}/></>:<p className="empty-copy">新建标签后输入网址。关闭工作台页面会保留标签。</p>}</section>;
}
function readActiveBrowser(){try{return localStorage.getItem("grok.active-browser.v1")||""}catch{return ""}}
function BrowserSurface({id}:{id:string}) {
 const host=useRef<HTMLDivElement>(null);
 useEffect(()=>{const element=host.current;if(!element)return;let last="",disposed=false;let frame=0;
 const sync=()=>{cancelAnimationFrame(frame);frame=requestAnimationFrame(()=>{if(disposed)return;const rect=element.getBoundingClientRect();const blocked=Boolean(document.querySelector('.ui-dialog,[role="menu"],.modal-backdrop,.add-palette-backdrop'));const bounds={x:Math.max(0,rect.x),y:Math.max(0,rect.y),width:Math.max(0,rect.width),height:Math.max(0,rect.height),visible:!blocked&&element.getClientRects().length>0};const signature=JSON.stringify(bounds);if(signature===last)return;last=signature;void window.grokDesktop.boundsWorkspaceBrowser(id,bounds).catch(()=>undefined)})};
 const resize=new ResizeObserver(sync);resize.observe(element);const mutations=new MutationObserver(sync);mutations.observe(document.body,{subtree:true,childList:true,attributes:true,attributeFilter:["hidden","class","data-state"]});window.addEventListener("resize",sync);sync();
 return()=>{disposed=true;cancelAnimationFrame(frame);resize.disconnect();mutations.disconnect();window.removeEventListener("resize",sync);void window.grokDesktop.boundsWorkspaceBrowser(id,{x:0,y:0,width:0,height:0,visible:false}).catch(()=>undefined)};
 },[id]);return <div className="browser-surface" ref={host} aria-label="隔离网页内容"/>;
}
