import { useEffect, useMemo, useState } from "react";
import { UiDialog } from "./ui/primitives";
import type { UiAction } from "./ui/ActionMenu";
export function flattenActions(actions: UiAction[], prefix = ""): UiAction[] { return actions.flatMap(action => action.children?.length ? flattenActions(action.children, `${prefix}${action.label} / `) : [{ ...action, label: `${prefix}${action.label}` }]); }
export function CommandSearch({ actions, onError }: { actions: UiAction[]; onError(message: string): void }) {
  const [open, setOpen] = useState(false); const [query, setQuery] = useState(""); const [index, setIndex] = useState(0);
  useEffect(() => { const show = () => { if (document.querySelector('[role="dialog"][aria-modal="true"]')) return; setQuery(""); setIndex(0); setOpen(true); }; const key = (event: KeyboardEvent) => { if (!event.isComposing && (event.ctrlKey || event.metaKey) && event.key.toLowerCase() === "k") { event.preventDefault(); show(); } }; window.addEventListener("grok:command-search", show); window.addEventListener("keydown", key); return () => { window.removeEventListener("grok:command-search", show); window.removeEventListener("keydown", key); }; }, []);
  const rows = useMemo(() => flattenActions(actions).filter(action => action.label.toLocaleLowerCase().includes(query.trim().toLocaleLowerCase())).slice(0, 100), [actions, query]);
  useEffect(()=>{document.getElementById(`command-${index}`)?.scrollIntoView({block:"nearest"});},[index]);
  const choose = async (action: UiAction | undefined) => { if (!action || action.disabled || !action.run) return; setOpen(false); try { await action.run(); } catch (error) { onError(error instanceof Error ? error.message : String(error)); } };
  return <UiDialog title="搜索命令和会话" open={open} onOpenChange={setOpen}><input className="command-search-input" autoFocus placeholder="搜索页面、操作或会话…" aria-label="搜索命令和会话" role="combobox" aria-expanded aria-controls="command-results" aria-activedescendant={rows[index] ? `command-${index}` : undefined} value={query} onChange={event => { setQuery(event.target.value); setIndex(0); }} onKeyDown={event => { if (event.nativeEvent.isComposing) return; if (event.key === "ArrowDown" || event.key === "ArrowUp") { event.preventDefault(); setIndex(value => Math.max(0,Math.min(rows.length - 1,value + (event.key === "ArrowDown" ? 1 : -1)))); } if (event.key === "Enter") { event.preventDefault(); void choose(rows[index]); } }}/><div id="command-results" className="command-results" role="listbox">{rows.map((action, i) => <button id={`command-${i}`} role="option" aria-selected={index === i} aria-disabled={action.disabled} key={action.id} className={index === i ? "selected" : ""} onMouseMove={() => setIndex(i)} onClick={() => void choose(action)}><span>{action.label}{action.reason && <small>{action.reason}</small>}</span><kbd>{action.shortcut}</kbd></button>)}{!rows.length && <p className="empty-copy">没有匹配的命令或会话</p>}</div><small className="command-search-hint">↑ ↓ 选择 · Enter 打开 · Esc 关闭</small></UiDialog>;
}
