import React,{useEffect,useRef,useState}from"react";
import type{RemoteGatewayState}from"../../../shared/remote";
import{Button}from"./ui/Button";
import { MobileDownloadCard } from "./MobileDownloadCard";
export function RemoteConnections(){
 const[state,setState]=useState<RemoteGatewayState&{qrDataUrl?:string}>(),[port,setPort]=useState("48975"),[busy,setBusy]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState(""),[address,setAddress]=useState(""),[portChanged,setPortChanged]=useState(false);
 const requestVersion=useRef(0),actionRunning=useRef(false);const selectedAddress=address&&state?.addresses.includes(address)?address:state?.addresses[0]||"";
 const pairedAddress=state?.pairing?new URL(state.pairing.uri).searchParams.get("host")||"":"";const qrCurrent=Boolean(state?.pairing&&pairedAddress===selectedAddress&&!busy);
 useEffect(()=>{let disposed=false;const refresh=()=>{if(actionRunning.current)return;const version=requestVersion.current;void window.grokDesktop.getRemoteState().then(next=>{if(!disposed&&version===requestVersion.current){setState(next);if(next.enabled)setPort(String(next.port))}}).catch(e=>{if(!disposed)setError(String(e))})};refresh();const timer=setInterval(refresh,2000);return()=>{disposed=true;clearInterval(timer)}},[]);
 const action=async(run:()=>Promise<RemoteGatewayState&{qrDataUrl?:string}>)=>{if(actionRunning.current)return;actionRunning.current=true;requestVersion.current++;setBusy(true);setError("");try{setState(await run())}catch(e){setError(e instanceof Error?e.message:String(e))}finally{actionRunning.current=false;setBusy(false)}};
 return <section className="remote-settings" aria-label="手机连接"><header><h3>连接安卓手机</h3><p>手机与电脑连接同一局域网，扫码后即可查看会话和继续任务。</p></header>
  <MobileDownloadCard/>
  <div className="remote-controls"><span className={`remote-status ${state?.enabled?"online":""}`}>{state?.enabled?`${state.hostName} · 可配对`:"尚未开启"}</span><Button variant={state?.enabled?"secondary":"primary"} loading={busy} onClick={()=>void action(()=>window.grokDesktop.setRemoteEnabled(!state?.enabled,portChanged?Number(port):undefined))}>{state?.enabled?"关闭手机连接":"开启手机连接"}</Button></div>
  {error&&<p role="alert" className="remote-error">{error}</p>}{state?.error&&<p role="alert">{state.error}</p>}{notice&&<p role="status">{notice}</p>}
  {state?.enabled&&<><ol style={{lineHeight:1.9,paddingLeft:22}}><li>安装配套 Grok Remote APK，无需开发工具。</li><li>在手机选择“扫码连接”，扫描下方二维码。</li><li>在电脑确认手机请求，手机会进入会话列表。</li></ol><Button disabled={busy||!selectedAddress} onClick={()=>void action(()=>window.grokDesktop.beginRemotePairing(address||undefined))}>{state.pairing?"刷新二维码":"配对新手机"}</Button>
   {state.pairing&&<div className="remote-pairing">{state.qrDataUrl&&qrCurrent&&<img src={state.qrDataUrl} alt="手机配对二维码" width={280} height={280}/>}<div><strong>{state.hostName}</strong><p>有效至 {new Date(state.pairing.expiresAt).toLocaleTimeString()}。扫码后请在电脑允许配对。</p><Button size="sm" disabled={!qrCurrent} onClick={()=>void navigator.clipboard.writeText(state.pairing!.uri)}>复制配对链接</Button><p>手机核验电脑身份后选择可达入口。切换地址会更新二维码。</p></div></div>}
   {state.pending.map(pair=><article className="remote-device pending" key={pair.id}><div><strong>{pair.name}</strong><span>请求访问此电脑的会话</span></div><Button size="sm" disabled={busy} onClick={()=>void action(()=>window.grokDesktop.decideRemotePair(pair.id,false))}>拒绝</Button><Button size="sm" variant="primary" disabled={busy} onClick={()=>void action(()=>window.grokDesktop.decideRemotePair(pair.id,true))}>允许配对</Button></article>)}
   <p>开启手机连接时，关闭窗口会继续在托盘运行。退出应用可从托盘菜单操作。</p>
  </>}
  <h4>已配对手机 · {state?.devices.length??0}</h4>{!state?.devices.length&&<p>尚未配对手机，完成上述三步即可连接。</p>}{state?.devices.map(device=><article className="remote-device" key={device.id}><div><strong>{device.name}</strong><span>{new Date(device.pairedAt).toLocaleString()}</span></div><Button size="sm" variant="danger" disabled={busy} onClick={()=>void action(()=>window.grokDesktop.revokeRemoteDevice(device.id))}>撤销访问</Button></article>)}
  <details style={{marginTop:18}}><summary>高级连接设置与诊断</summary><div className="remote-addresses"><strong>当前电脑的网络入口</strong>{state?.addresses.length?<><select aria-label="手机连接地址" value={selectedAddress} disabled={busy} onChange={event=>{const next=event.target.value;setAddress(next);if(state.pairing)void action(()=>window.grokDesktop.beginRemotePairing(next))}}>{state.addresses.map(value=>{const option=state.addressOptions?.find(row=>row.url===value);return <option key={value} value={value}>{option?.interfaceName} · {value}{option?.kind==="vpn"?"（虚拟网络）":option?.recommended?"（优先探测）":""}</option>})}</select><code>{selectedAddress}</code></>:<p>未发现可用局域网地址，请检查网络连接。</p>}</div><label>端口<input type="number" min={1024} max={65535} value={port} disabled={state?.enabled||busy} onChange={event=>{setPort(event.target.value);setPortChanged(true)}}/></label><p>默认自动选择可用端口。网卡排序不代表手机已连通；外网需要已有私有 VPN。</p><Button size="sm" disabled={busy} onClick={()=>{setBusy(true);void window.grokDesktop.configureRemotePush().then(value=>setNotice(value.configured?"云端推送已配置，请在手机设备页启用。":"尚未配置云端推送")).catch(error=>setError(String(error))).finally(()=>setBusy(false))}}>配置云端推送（可选）</Button>{state?.connectionDiagnostics&&<><p>TCP 到达 {state.connectionDiagnostics.tcp} 次 · TLS 成功 {state.connectionDiagnostics.tls} 次 · API 请求 {state.connectionDiagnostics.requests} 次</p><p>最近握手状态：{state.connectionDiagnostics.lastTlsError||"未记录错误"}</p></>}<p>连接不到时，检查双方网络是否允许设备互访，以及 Windows 对此应用的网络许可。</p></details>
 </section>;
}
