import { useEffect, useRef, useState, type ReactNode } from "react";
import * as Dialog from "@radix-ui/react-dialog";
import { initialLayout, leaves, openTarget, splitPane, closePane, moveTab, mapPane, restoreLayout, targetKey, workspaceKey, removeTabs, type WorkspaceLayout, type PaneNode, type ContentTarget } from "../workspace-layout";
import { useAppStore } from "../store";
import { useWorkbenchStore, type EditorTabState } from "../workbench-store";
import { decodeMediaArtifact } from "../media-artifact-target";
import { PaneReader } from "./PaneReader";
import { ActionMenu, ActionContextMenu, type UiAction } from "./ui/ActionMenu";
const KEY="grok.workbench-layout.v1";
const MIME="application/x-grok-workbench-tab";
function restore():WorkspaceLayout {try{return restoreLayout(JSON.parse(localStorage.getItem(KEY)||"null"))}catch{return initialLayout()}}
type CloseChoice = "save" | "discard";
export function WorkspaceDeck({target,hidden,children,onActivate,onError,renderBackground}:{target?:ContentTarget;hidden?:boolean;children:ReactNode;renderBackground?(target:ContentTarget):ReactNode;onActivate(target:ContentTarget):Promise<void>;onError(message:string):void}) {
 const [layout,setLayout]=useState(restore);const layoutRef=useRef(layout);layoutRef.current=layout;
 const [switching,setSwitching]=useState(false);const switchingRef=useRef(false);
 const [dragOver,setDragOver]=useState("");
 const [recent,setRecent]=useState<ContentTarget[]>([]);
 const [workspaceOrder,setWorkspaceOrder]=useState<string[]>(()=>{try{const value=JSON.parse(localStorage.getItem("grok.workspace-tabs.v1")||"[]");return Array.isArray(value)?value.filter((v:unknown)=>typeof v==="string"):[]}catch{return []}});
 const ignoredTargets=useRef(new Set<string>());
 const [closeRequest,setCloseRequest]=useState<{files:EditorTabState[];resolve(value:Record<string,CloseChoice>|null):void}>();
 const closeRequestRef=useRef(closeRequest);closeRequestRef.current=closeRequest;
 useEffect(()=>()=>closeRequestRef.current?.resolve(null),[]);
 const [choices,setChoices]=useState<Record<string,CloseChoice>>({});
 const key=target?targetKey(target):"";
 useEffect(()=>{const reveal=(event:Event)=>{if(switchingRef.current)return;const id=(event as CustomEvent<{nodeId:string}>).detail.nodeId;const next:ContentTarget={kind:"subagent",workspace:useAppStore.getState().settings?.activeWorkspace||target?.workspace||"",id,title:"子会话"};ignoredTargets.current.delete(targetKey(next));setLayout(value=>openTarget(value,value.focusedPane,next))};window.addEventListener("grok:reveal-subagent",reveal);return()=>window.removeEventListener("grok:reveal-subagent",reveal)},[target?.workspace]);
 useEffect(()=>{if(target&&!switchingRef.current&&!ignoredTargets.current.has(key))setLayout(value=>openTarget(value,value.focusedPane,target))},[key]);
 useEffect(()=>{if(!target)return;setLayout(value=>({...value,root:leaves(value.root).reduce((root,pane)=>mapPane(root,pane.id,n=>n.kind==="leaf"?{...n,tabs:n.tabs.map(tab=>targetKey(tab)===key?{...tab,title:target.title}:tab)}:n),value.root)}))},[key,target?.title]);
 useEffect(()=>{const timer=setTimeout(()=>{try{localStorage.setItem(KEY,JSON.stringify(layout))}catch{}},200);return()=>clearTimeout(timer)},[layout]);
 useEffect(()=>{const open=()=>{if(target&&!switchingRef.current){ignoredTargets.current.delete(targetKey(target));setLayout(value=>openTarget(value,value.focusedPane,target))}};window.addEventListener("grok:reveal-current",open);return()=>window.removeEventListener("grok:reveal-current",open)},[target]);
 useEffect(()=>{const invalid=(event:Event)=>{const id=(event as CustomEvent<{sessionId:string}>).detail.sessionId;setLayout(value=>removeTabs(value,undefined,tab=>(tab.kind==="session"&&tab.id===id)||(tab.kind==="artifact"&&decodeMediaArtifact(tab.id)?.sessionId===id)||(tab.kind==="subagent"&&tab.id.startsWith(`session:${id}:subagent:`))));setRecent(rows=>rows.filter(tab=>!((tab.kind==="session"&&tab.id===id)||(tab.kind==="artifact"&&decodeMediaArtifact(tab.id)?.sessionId===id)||(tab.kind==="subagent"&&tab.id.startsWith(`session:${id}:subagent:`)))))};window.addEventListener("grok:session-deleted",invalid);return()=>window.removeEventListener("grok:session-deleted",invalid)},[]);
 useEffect(()=>{const invalid=(event:Event)=>{const cwd=(event as CustomEvent<{cwd:string}>).detail.cwd;const matches=(tab:ContentTarget)=>workspaceKey(tab.workspace)===workspaceKey(cwd);setLayout(value=>removeTabs(value,undefined,matches));setRecent(rows=>rows.filter(tab=>!matches(tab)))};window.addEventListener("grok:project-deleted",invalid);return()=>window.removeEventListener("grok:project-deleted",invalid)},[]);
 const activate=async(paneId:string,next:ContentTarget|undefined)=>{if(switchingRef.current||!next)return false;switchingRef.current=true;setSwitching(true);try{await onActivate(next);setLayout(value=>openTarget(value,paneId,next));return true}catch(error){onError(`${next.title}：${error instanceof Error?error.message:String(error)}。可以重试或关闭此标签。`);return false}finally{switchingRef.current=false;setSwitching(false)}};
 const requestClose=async(paneId:string|undefined,predicate:(tab:ContentTarget)=>boolean,removePane=false,reset=false)=>{
  if(switchingRef.current)return;switchingRef.current=true;setSwitching(true);
  try{
   const snapshot=layoutRef.current;const selected=leaves(snapshot.root).filter(p=>!paneId||p.id===paneId).flatMap(p=>p.tabs.filter(predicate));
   if(!selected.length&&!removePane&&!reset)return;
   let next=removeTabs(snapshot,paneId,predicate);if(removePane&&paneId)next=closePane(next,paneId);
   const remaining=leaves(next.root).flatMap(p=>p.tabs);
   const closingFiles=useWorkbenchStore.getState().tabs.filter(file=>selected.some(t=>t.kind==="file"&&t.id===file.key)&&!remaining.some(t=>t.kind==="file"&&t.id===file.key));
   const dirty=closingFiles.filter(file=>file.dirty);
   if(dirty.length){
    setChoices(Object.fromEntries(dirty.map(file=>[file.key,"save"])));
    const decisions=await new Promise<Record<string,CloseChoice>|null>(resolve=>setCloseRequest({files:dirty,resolve}));
    if(!decisions)return;
    for(const file of dirty){if(decisions[file.key]!=="save")continue;const current=useWorkbenchStore.getState().tabs.find(t=>t.key===file.key);if(!current)continue;
     const result=await window.grokDesktop.saveEditorDocument({workspacePath:current.document.workspacePath,path:current.document.path,content:current.buffer,encoding:current.document.encoding,lineEnding:current.document.lineEnding,expectedHash:current.document.hash,expectedModifiedAt:current.document.modifiedAt});
     if(!result.document){useWorkbenchStore.getState().setConflict(current.key,result.conflict);throw Error(`未关闭标签：${current.document.relativePath} 存在保存冲突`)}useWorkbenchStore.getState().acceptSave(result.document,current.buffer);
     if(useWorkbenchStore.getState().tabs.find(t=>t.key===current.key)?.dirty)throw Error(`保存期间文件继续发生修改，保留标签：${current.document.relativePath}`);
    }
   }
   const focused=leaves(next.root).find(p=>p.id===next.focusedPane)!;const nextTarget=focused.tabs.find(t=>targetKey(t)===focused.activeTab);
   // A stale neighbour must never prevent closing an unwanted/stale tab.
   if(nextTarget&&targetKey(nextTarget)!==key){try{await onActivate(nextTarget)}catch(error){onError(String(error));next={...next,root:mapPane(next.root,focused.id,n=>n.kind==="leaf"?{...n,activeTab:undefined}:n)}}}
   selected.forEach(tab=>ignoredTargets.current.add(targetKey(tab)));
   if(closingFiles.length&&!nextTarget)closingFiles.forEach(file=>ignoredTargets.current.add(targetKey({kind:"workspace",workspace:file.document.workspacePath,id:"files",title:"文件"})));
   closingFiles.forEach(file=>useWorkbenchStore.getState().closeTab(file.key));
   setRecent(rows=>[...selected,...rows].filter((tab,index,all)=>all.findIndex(t=>targetKey(t)===targetKey(tab))===index).slice(0,20));
   setLayout(reset?initialLayout():next);
   if(reset)window.dispatchEvent(new Event("grok:layout-reset-complete"));
  }catch(error){onError(error instanceof Error?error.message:String(error))}finally{switchingRef.current=false;setSwitching(false)}
 };
 useEffect(()=>{const reset=()=>{void requestClose(undefined,()=>true,false,true)};window.addEventListener("grok:reset-layout",reset);return()=>window.removeEventListener("grok:reset-layout",reset)},[key]);
 useEffect(()=>{const closeFile=(event:Event)=>{const id=(event as CustomEvent<{key:string}>).detail.key;if(!leaves(layoutRef.current.root).some(p=>p.tabs.some(t=>t.kind==="file"&&t.id===id)))return;event.preventDefault();void requestClose(undefined,t=>t.kind==="file"&&t.id===id)};window.addEventListener("grok:close-file-view",closeFile);return()=>window.removeEventListener("grok:close-file-view",closeFile)},[key]);
 useEffect(()=>{const reveal=(event:Event)=>{const next=(event as CustomEvent<ContentTarget>).detail;if(switchingRef.current)return;ignoredTargets.current.delete(targetKey(next));setLayout(value=>openTarget(value,value.focusedPane,next))};window.addEventListener("grok:reveal-file",reveal);return()=>window.removeEventListener("grok:reveal-file",reveal)},[]);
 const split=async(paneId:string,axis:"horizontal"|"vertical")=>{const snapshot=layoutRef.current;const source=leaves(snapshot.root).find(p=>p.id===paneId);const tab=source?.tabs.find(t=>targetKey(t)===source.activeTab);try{const next=splitPane(snapshot,paneId,axis,crypto.randomUUID());if(tab&&!await activate(paneId,tab))return;setLayout(next)}catch(error){onError(String(error))}};
 const drop=async(data:{pane:string;key:string},destination:string,index:number)=>{if(switchingRef.current)return;const source=leaves(layoutRef.current.root).find(p=>p.id===data.pane);const tab=source?.tabs.find(t=>targetKey(t)===data.key);if(!tab||!await activate(destination,tab))return;setLayout(value=>moveTab(value,data.pane,destination,data.key,index))};
 const allTabs=leaves(layout.root).flatMap(p=>p.tabs);const workspaces=[...new Map([...workspaceOrder,...allTabs.map(t=>t.workspace)].map(path=>[workspaceKey(path),path])).values()].filter(workspace=>allTabs.some(t=>workspaceKey(t.workspace)===workspaceKey(workspace)));
 const actions=(pane:Extract<PaneNode,{kind:"leaf"}>,tab?:ContentTarget):UiAction[]=>[
  {id:"close-tab",label:"关闭标签",disabled:!tab,run:()=>requestClose(pane.id,t=>targetKey(t)===targetKey(tab!))},
  {id:"close-others",label:"关闭其他标签",disabled:!tab||pane.tabs.length<2,run:()=>requestClose(pane.id,t=>targetKey(t)!==targetKey(tab!))},
  {id:"close-right",label:"关闭右侧标签",disabled:!tab||pane.tabs.at(-1)===tab,run:()=>{const index=pane.tabs.indexOf(tab!);const keys=new Set(pane.tabs.slice(index+1).map(targetKey));return requestClose(pane.id,t=>keys.has(targetKey(t)))}},
  {id:"close-all",label:"关闭此窗格全部标签",disabled:!pane.tabs.length,run:()=>requestClose(pane.id,()=>true)},
  {id:"reopen",label:"重新打开最近关闭的标签",disabled:!recent.length,run:async()=>{if(await activate(pane.id,recent[0]))setRecent(rows=>rows.slice(1))}},
 ];
 const render=(node:PaneNode):ReactNode=>node.kind==="split"?<div key={node.id} className={`workbench-split ${node.axis}`}><div style={{flex:`${node.ratio} 1 0`}}>{render(node.first)}</div><div className="pane-divider" role="separator" aria-orientation={node.axis==="horizontal"?"vertical":"horizontal"} aria-valuenow={Math.round(node.ratio*100)} aria-valuemin={15} aria-valuemax={85} aria-label="调整窗格尺寸" tabIndex={0} onKeyDown={e=>{if(["ArrowLeft","ArrowUp","ArrowRight","ArrowDown"].includes(e.key)){e.preventDefault();setLayout(v=>({...v,root:mapPane(v.root,node.id,n=>n.kind==="split"?{...n,ratio:Math.max(.15,Math.min(.85,n.ratio+(["ArrowRight","ArrowDown"].includes(e.key)?.05:-.05)))}:n)}))}}} onPointerDown={e=>e.currentTarget.setPointerCapture(e.pointerId)} onPointerMove={e=>{if(!e.currentTarget.hasPointerCapture(e.pointerId))return;const r=e.currentTarget.parentElement!.getBoundingClientRect();const ratio=Math.max(.15,Math.min(.85,node.axis==="horizontal"?(e.clientX-r.left)/r.width:(e.clientY-r.top)/r.height));setLayout(v=>({...v,root:mapPane(v.root,node.id,n=>n.kind==="split"?{...n,ratio}:n)}))}} onPointerUp={e=>e.currentTarget.releasePointerCapture(e.pointerId)}/><div style={{flex:`${1-node.ratio} 1 0`}}>{render(node.second)}</div></div>:<section className={`workbench-pane ${layout.focusedPane===node.id?"focused":""} ${dragOver===node.id?"drop-target":""}`} key={node.id} aria-label="内容窗格" onDragOver={e=>{if(e.dataTransfer.types.includes(MIME)){e.preventDefault();setDragOver(node.id)}}} onDragLeave={()=>setDragOver("")} onDrop={e=>{e.preventDefault();setDragOver("");try{void drop(JSON.parse(e.dataTransfer.getData(MIME)),node.id,node.tabs.length)}catch{}}}>
 <header className={`pane-tabs${node.tabs.length < 2 ? " single" : ""}`}><div role="tablist" aria-label="内容标签">{node.tabs.map((tab,index)=><ActionContextMenu key={targetKey(tab)} actions={actions(node,tab)} onError={onError}><div className="content-tab"><button role="tab" aria-selected={node.activeTab===targetKey(tab)} draggable title={`${tab.title} · ${tab.workspace}`} onDragStart={e=>e.dataTransfer.setData(MIME,JSON.stringify({pane:node.id,key:targetKey(tab)}))} onDragOver={e=>{if(e.dataTransfer.types.includes(MIME))e.preventDefault()}} onDrop={e=>{e.preventDefault();e.stopPropagation();setDragOver("");try{void drop(JSON.parse(e.dataTransfer.getData(MIME)),node.id,index)}catch{}}} onClick={()=>void activate(node.id,tab)}>{tab.title}</button><button className="content-tab-close" aria-label={`关闭标签 ${tab.title}`} title="关闭视图，不结束后台任务" disabled={switching} onClick={()=>void requestClose(node.id,t=>targetKey(t)===targetKey(tab))}>×</button></div></ActionContextMenu>)}</div><ActionMenu trigger={<button aria-label="窗格操作" disabled={switching}>⋯</button>} onError={onError} actions={[...actions(node,node.tabs.find(t=>targetKey(t)===node.activeTab)),{id:"horizontal",label:"向右分屏",disabled:leaves(layout.root).length>=4||!node.activeTab,run:()=>split(node.id,"horizontal")},{id:"vertical",label:"向下分屏",disabled:leaves(layout.root).length>=4||!node.activeTab,run:()=>split(node.id,"vertical")},{id:"close-pane",label:"关闭窗格",disabled:leaves(layout.root).length===1,run:()=>requestClose(node.id,()=>true,true)},{id:"close-everywhere",label:"关闭所有窗格的全部标签",disabled:!allTabs.length,run:()=>requestClose(undefined,()=>true)}]}/></header>
 {!node.activeTab?<div className="empty-copy"><h3>暂无打开内容</h3><p>从侧栏选择会话，或打开文件。关闭视图不会结束后台任务。</p>{target&&<button onClick={()=>void activate(node.id,target)}>返回当前内容</button>}</div>:layout.focusedPane===node.id?children:renderBackground?.(node.tabs.find(t=>targetKey(t)===node.activeTab)!)??<PaneReader paneId={node.id} target={node.tabs.find(t=>targetKey(t)===node.activeTab)} onActivate={()=>void activate(node.id,node.tabs.find(t=>targetKey(t)===node.activeTab))}/>}</section>;
 const finish=(value:Record<string,CloseChoice>|null)=>{closeRequest?.resolve(value);setCloseRequest(undefined)};
 return <div className="workspace-deck" hidden={hidden} aria-busy={switching}><nav className="workspace-tabs" aria-label="打开的工作区" hidden>{workspaces.map(workspace=><button key={workspace} className={workspaceKey(target?.workspace||"")===workspaceKey(workspace)?"active":""} title={workspace} draggable onDragStart={e=>e.dataTransfer.setData("application/x-grok-workspace",workspace)} onDragOver={e=>{if(e.dataTransfer.types.includes("application/x-grok-workspace"))e.preventDefault()}} onDrop={e=>{e.preventDefault();const source=e.dataTransfer.getData("application/x-grok-workspace");if(!workspaces.includes(source))return;const order=workspaces.filter(path=>path!==source);order.splice(order.indexOf(workspace),0,source);setWorkspaceOrder(order);try{localStorage.setItem("grok.workspace-tabs.v1",JSON.stringify(order))}catch{}}} onClick={()=>{const tab=allTabs.findLast(t=>workspaceKey(t.workspace)===workspaceKey(workspace));void activate(layout.focusedPane,tab)}}>{workspace.split(/[\\/]/).filter(Boolean).at(-1)||"工作区"}</button>)}</nav><div className="workspace-pane-tree">{render(layout.root)}</div>{switching&&!closeRequest&&<div className="pane-switching" role="status">正在处理…</div>}
 <Dialog.Root open={Boolean(closeRequest)} onOpenChange={open=>{if(!open)finish(null)}}><Dialog.Portal><Dialog.Overlay className="ui-dialog-overlay"/><Dialog.Content className="ui-dialog"><Dialog.Title>关闭前处理未保存文件</Dialog.Title><Dialog.Description>先选择每个文件的处理方式；取消会保留所有标签。</Dialog.Description>{closeRequest?.files.map(file=><label className="close-file-choice" key={file.key}><span>{file.document.relativePath}</span><select value={choices[file.key]||"save"} onChange={e=>setChoices(v=>({...v,[file.key]:e.target.value as CloseChoice}))}><option value="save">保存后关闭</option><option value="discard">放弃修改</option></select></label>)}<div className="button-row"><button onClick={()=>finish(null)}>取消</button><button onClick={()=>finish(choices)}>确认并关闭</button></div></Dialog.Content></Dialog.Portal></Dialog.Root></div>;
}
