import { ipcMain, type BrowserWindow, type IpcMainInvokeEvent } from "electron";
import type { AppController } from "./app-controller";
import type { AgentDashboardQuery, AgentDefinitionSaveInput, AppSettings, Attachment, AutomationGlobalPolicy, AutomationTaskInput, ComposerCapabilitySelection, ComputerUseSettings, CustomProviderInput, EditorSaveInput, ExecutionProfileLaunchInput, ExecutionProfileSaveInput, GitDiscardInput, GitHunkActionInput, GitReviewScope, McpServerInput, MemoryDeletePreview, MemoryRememberPreview, MemorySaveInput, MemorySettings, OnboardingState, PersonaDefinitionSaveInput, ProviderConnectionDraft, ReasoningEffort, SessionExecutionProfile, SessionMode, ThemeSettings, WorktreeCreateInput, WorkspaceTreeOptions } from "../shared/types";
import { isTrustedRendererFrame, type RendererTrustPolicy } from "./security-policy";

export function registerIpc(controller: AppController, window: BrowserWindow, policy: RendererTrustPolicy): void {
  const handle = <Args extends unknown[]>(channel: string, action: (...args: Args) => unknown): void => {
    ipcMain.handle(channel, (event, ...args) => {
      assertTrustedIpcSender(event, window, policy);
      return action(...args as Args);
    });
  };

  handle("app:bootstrap", () => controller.bootstrap());
  handle("app:build-info", () => controller.getBuildInfo());
  handle("onboarding:get", () => controller.getOnboarding());
  handle("onboarding:update", (patch: Partial<OnboardingState>) => controller.updateOnboarding(patch));
  handle("onboarding:reset", () => controller.resetOnboarding());
  handle("diagnostics:run", () => controller.runDiagnostics());
  handle("diagnostics:cli-capabilities", (force?: boolean) => controller.getCliCapabilities(force));
  handle("diagnostics:support-preview", () => controller.previewSupportBundle());
  handle("diagnostics:support-export", () => controller.exportSupportBundle());
  handle("app-update:check", (force?: boolean) => controller.checkAppUpdate(force));
  handle("app-update:open", (url?: string) => controller.openAppRelease(url));
  handle("workspace:choose", () => controller.chooseWorkspace());
  handle("workspace:set", (cwd: string) => controller.setWorkspace(cwd));
  handle("workspace:discover", (force?: boolean) => controller.discoverWorkspaces(force));
  handle("workspace:pin", (cwd: string, pinned: boolean) => controller.pinWorkspace(cwd, pinned));
  handle("workspace:search-files", (cwd: string, query: string, limit?: number) => controller.searchWorkspaceFiles(cwd, query, limit));
  handle("workspace:tree:list", (cwd: string, directoryPath?: string, options?: WorkspaceTreeOptions) => controller.listWorkspaceTree(cwd, directoryPath, options));
  handle("editor:open", (cwd: string, path: string) => controller.openEditorDocument(cwd, path));
  handle("editor:save", (input: EditorSaveInput) => controller.saveEditorDocument(input));
  handle("editor:create-file", (cwd: string, path: string, content?: string) => controller.createEditorFile(cwd, path, content));
  handle("editor:create-directory", (cwd: string, path: string) => controller.createEditorDirectory(cwd, path));
  handle("editor:rename", (cwd: string, path: string, targetPath: string) => controller.renameEditorPath(cwd, path, targetPath));
  handle("editor:delete", (cwd: string, path: string, confirmed: boolean) => controller.deleteEditorPath(cwd, path, confirmed));
  handle("editor:reveal", (cwd: string, path: string) => controller.revealEditorPath(cwd, path));
  handle("git:trust:get", (cwd: string) => controller.getGitRepositoryTrust(cwd));
  handle("git:capability", (cwd: string) => controller.getGitWorkspaceCapability(cwd));
  handle("git:trust:set", (cwd: string, repositoryRoot: string, trusted: boolean) => controller.setGitRepositoryTrust(cwd, repositoryRoot, trusted));
  handle("git:status", (cwd: string) => controller.getGitStatus(cwd));
  handle("git:diff", (cwd: string, staged: boolean, path?: string) => controller.getGitDiff(cwd, staged, path));
  handle("git:review", (cwd: string, scope: GitReviewScope) => controller.getGitReview(cwd, scope));
  handle("git:review:index", (cwd: string, scope: GitReviewScope) => controller.getGitReviewIndex(cwd, scope));
  handle("git:review:file", (cwd: string, scope: GitReviewScope, snapshotId: string, fileId: string) => controller.getGitReviewFileDetail(cwd, scope, snapshotId, fileId));
  handle("git:review:hunk", (cwd: string, input: GitHunkActionInput) => controller.applyGitReviewHunk(cwd, input));
  handle("git:stage", (cwd: string, paths?: string[]) => controller.stageGitChanges(cwd, paths));
  handle("git:unstage", (cwd: string, paths?: string[]) => controller.unstageGitChanges(cwd, paths));
  handle("git:commit", (cwd: string, message: string) => controller.commitGitChanges(cwd, message));
  handle("git:branches", (cwd: string) => controller.listGitBranches(cwd));
  handle("git:branch:create", (cwd: string, name: string, startPoint?: string) => controller.createGitBranch(cwd, name, startPoint));
  handle("git:branch:switch", (cwd: string, name: string) => controller.switchGitBranch(cwd, name));
  handle("git:history", (cwd: string, limit?: number) => controller.listGitHistory(cwd, limit));
  handle("git:commit:details", (cwd: string, hash: string) => controller.getGitCommitDetails(cwd, hash));
  handle("git:discard", (cwd: string, input: GitDiscardInput) => controller.discardGitChanges(cwd, input));
  handle("git:pull", (cwd: string, operationId: string) => controller.pullGitRepository(cwd, operationId));
  handle("git:push", (cwd: string, operationId: string) => controller.pushGitRepository(cwd, operationId));
  handle("git:cancel", (operationId: string) => controller.cancelGitOperation(operationId));
  handle("worktree:list", (cwd: string) => controller.listWorktrees(cwd));
  handle("worktree:create", (input: WorktreeCreateInput) => controller.createWorktree(input));
  handle("worktree:apply:preview", (cwd: string, worktreeId: string) => controller.previewWorktreeApply(cwd, worktreeId));
  handle("worktree:apply", (cwd: string, worktreeId: string, confirmationToken: string, confirmed: boolean, cleanup?: boolean) => controller.applyWorktree(cwd, worktreeId, confirmationToken, confirmed, cleanup));
  handle("worktree:remove", (cwd: string, worktreeId: string, confirmed: boolean) => controller.removeWorktree(cwd, worktreeId, confirmed));
  handle("worktree:gc:preview", (cwd: string) => controller.previewWorktreeGc(cwd));
  handle("worktree:gc", (cwd: string, confirmationToken: string, confirmed: boolean) => controller.gcWorktrees(cwd, confirmationToken, confirmed));
  handle("memory:layout", (cwd: string) => controller.resolveMemoryLayout(cwd));
  handle("memory:settings:get", (cwd: string) => controller.getMemorySettings(cwd));
  handle("memory:settings:update", (cwd: string, patch: Partial<Pick<MemorySettings, "enabled" | "saveOnSessionEnd" | "autoDream">>, sessionId?: string) => controller.updateMemorySettings(cwd, patch, sessionId));
  handle("memory:list", (cwd: string, query?: string) => controller.listMemory(cwd, query));
  handle("memory:save", (input: MemorySaveInput) => controller.saveMemory(input));
  handle("memory:remember:preview", (cwd: string, scope: "global" | "workspace", text: string) => controller.previewRemember(cwd, scope, text));
  handle("memory:remember", (preview: MemoryRememberPreview, confirmationToken: string, confirmed: boolean, sessionId?: string) => controller.rememberMemory(preview, confirmationToken, confirmed, sessionId));
  handle("memory:structured:list", (cwd: string, scope?: "global" | "workspace") => controller.listMemoryStructuredEntries(cwd, scope));
  handle("memory:structured:delete:preview", (cwd: string, entryId: string) => controller.previewDeleteMemoryEntry(cwd, entryId));
  handle("memory:structured:delete", (preview: MemoryDeletePreview, confirmationToken: string, confirmed: boolean) => controller.deleteMemoryEntry(preview, confirmationToken, confirmed));
  handle("memory:session:delete", (cwd: string, entryId: string, confirmed: boolean) => controller.deleteSessionMemory(cwd, entryId, confirmed));
  handle("memory:clear", (cwd: string, scope: "workspace" | "global" | "all", confirmed: boolean) => controller.clearMemory(cwd, scope, confirmed));
  handle("memory:command", (sessionId: string, command: "flush" | "dream") => controller.runMemoryCommand(sessionId, command));
  handle("agents:list", (cwd: string) => controller.listAgentDefinitions(cwd));
  handle("agents:validate", (rawMarkdown: string, expectedName?: string) => controller.validateAgentDefinition(rawMarkdown, expectedName));
  handle("agents:save", (input: AgentDefinitionSaveInput) => controller.saveAgentDefinition(input));
  handle("agents:copy", (cwd: string, sourcePath: string, targetSource: "user" | "project", newName: string) => controller.copyAgentDefinition(cwd, sourcePath, targetSource, newName));
  handle("agents:rename", (cwd: string, sourcePath: string, newName: string) => controller.renameAgentDefinition(cwd, sourcePath, newName));
  handle("agents:toggle", (cwd: string, sourcePath: string, enabled: boolean) => controller.setAgentDefinitionEnabled(cwd, sourcePath, enabled));
  handle("agents:delete", (cwd: string, sourcePath: string, confirmed: boolean) => controller.deleteAgentDefinition(cwd, sourcePath, confirmed));
  handle("personas:list", (cwd: string) => controller.listPersonaDefinitions(cwd));
  handle("personas:validate", (rawToml: string) => controller.validatePersonaDefinition(rawToml));
  handle("personas:save", (input: PersonaDefinitionSaveInput) => controller.savePersonaDefinition(input));
  handle("personas:copy", (cwd: string, sourcePath: string, targetSource: "user" | "project", newName: string) => controller.copyPersonaDefinition(cwd, sourcePath, targetSource, newName));
  handle("personas:rename", (cwd: string, sourcePath: string, newName: string) => controller.renamePersonaDefinition(cwd, sourcePath, newName));
  handle("personas:toggle", (cwd: string, sourcePath: string, enabled: boolean) => controller.setPersonaDefinitionEnabled(cwd, sourcePath, enabled));
  handle("personas:delete", (cwd: string, sourcePath: string, confirmed: boolean) => controller.deletePersonaDefinition(cwd, sourcePath, confirmed));
  handle("profiles:list", (cwd: string) => controller.listExecutionProfiles(cwd));
  handle("profiles:validate", (profile: SessionExecutionProfile) => controller.validateExecutionProfile(profile));
  handle("profiles:save", (input: ExecutionProfileSaveInput) => controller.saveExecutionProfile(input));
  handle("profiles:delete", (cwd: string, profileId: string, confirmed: boolean) => controller.deleteExecutionProfile(cwd, profileId, confirmed));
  handle("profiles:assignment", (sessionId: string) => controller.getSessionExecutionAssignment(sessionId));
  handle("dashboard:get", (query: AgentDashboardQuery) => controller.getAgentDashboard(query));
  handle("dashboard:stop", (nodeId: string) => controller.stopAgentDashboardNode(nodeId));
  handle("dashboard:clear", (nodeId?: string) => controller.clearAgentDashboardRecord(nodeId));
  handle("attachment:inspect-privacy", (cwd: string, attachments: Attachment[]) => controller.inspectAttachmentPrivacy(cwd, attachments));
  handle("session:list", (cwd?: string, query?: string) => controller.listSessions(cwd, query));
  handle("session:create", (input: string | ExecutionProfileLaunchInput) => controller.createSession(input));
  handle("session:open", (cwd: string, id: string) => controller.openSession(cwd, id));
  handle("session:rename", (id: string, title: string) => controller.renameSession(id, title));
  handle("session:delete", (cwd: string, id: string) => controller.deleteSession(cwd, id));
  handle("session:clear", (cwd: string, keep?: string) => controller.clearSessions(cwd, keep));
  handle("session:pin", (id: string, pinned: boolean) => controller.pinSession(id, pinned));
  handle("session:export-markdown", (cwd: string, id: string) => controller.exportSessionMarkdown(cwd, id));
  handle("session:media-capabilities", (id: string) => controller.getMediaCapabilities(id));
  handle("session:send", (id: string, text: string, attachments: Attachment[], clientMessageId?: string) => controller.sendPrompt(id, text, attachments, clientMessageId));
  handle("ui-fixture:get", () => controller.getOfflineUiFixture());
  handle("session:enqueue", (id: string, text: string, attachments: Attachment[], clientMessageId?: string) => controller.enqueuePrompt(id, text, attachments, clientMessageId));
  handle("session:interject", (id: string, text: string, attachments: Attachment[], clientMessageId?: string) => controller.interjectPrompt(id, text, attachments, clientMessageId));
  handle("session:queue:edit", (sessionId: string, id: string, text: string) => controller.editQueuedPrompt(sessionId, id, text));
  handle("session:queue:remove", (sessionId: string, id: string) => controller.removeQueuedPrompt(sessionId, id));
  handle("session:queue:reorder", (sessionId: string, id: string, position: number) => controller.reorderQueuedPrompt(sessionId, id, position));
  handle("session:queue:clear", (sessionId: string) => controller.clearPromptQueue(sessionId));
  handle("session:queue:interject", (sessionId: string, id: string, text?: string) => controller.interjectQueuedPrompt(sessionId, id, text));
  handle("session:fork", (sessionId: string, pointId?: string, launch?: ExecutionProfileLaunchInput) => controller.forkSession(sessionId, pointId, launch));
  handle("session:rewind-points", (sessionId: string) => controller.listRewindPoints(sessionId));
  handle("session:rewind", (sessionId: string, pointId: string, mode: "conversation" | "conversation-and-files" | "files") => controller.rewindSession(sessionId, pointId, mode));
  handle("session:archive", (sessionId: string, archived: boolean) => controller.archiveSession(sessionId, archived));
  handle("tasks:list", () => controller.listBackgroundTasks());
  handle("tasks:kill", (id: string) => controller.killBackgroundTask(id));
  handle("inbox:list", () => controller.listInbox());
  handle("inbox:mark-read", (id: string, read: boolean) => controller.markInboxRead(id, read));
  handle("inbox:clear", () => controller.clearInbox());
  handle("session:cancel", (id: string) => controller.cancelSession(id));
  handle("session:model", (id: string, model: string) => controller.setModel(id, model));
  handle("session:effort", (id: string, effort: ReasoningEffort) => controller.setEffort(id, effort));
  handle("session:mode", (id: string, mode: SessionMode) => controller.setMode(id, mode));
  handle("permission:respond", (id: string, requestId: string | number, optionId: string) => controller.respondPermission(id, requestId, optionId));
  handle("question:respond", (id: string, requestId: string | number, answers: Record<string, string>) => controller.respondQuestion(id, requestId, answers));
  handle("plan:respond", (id: string, requestId: string | number | undefined, verdict: "approved" | "rejected" | "cancelled", comment?: string) => controller.respondPlan(id, requestId, verdict, comment));
  handle("attachments:pick", () => controller.pickAttachments());
  handle("attachments:pick-folders", () => controller.pickAttachmentFolders());
  handle("attachments:paths", (paths: string[]) => controller.attachmentsFromPaths(paths));
  handle("system:open-path", (path: string) => controller.openPath(path));
  handle("system:open-external", (url: string) => controller.openExternal(url));
  handle("settings:get", () => controller.getSettings());
  handle("settings:update", (patch: Partial<AppSettings>) => controller.updateSettings(patch));
  handle("theme:get", () => controller.getTheme());
  handle("theme:update", (patch: Partial<ThemeSettings>) => controller.updateTheme(patch));
  handle("theme:pick-background", () => controller.pickThemeBackground());
  handle("theme:remove-background", () => controller.removeThemeBackground());
  handle("auth:list", () => controller.listAccounts());
  handle("auth:login-device", () => controller.loginDevice());
  handle("auth:login-api-key", (label: string, key: string) => controller.loginApiKey(label, key));
  handle("auth:logout", () => controller.logout());
  handle("auth:switch", (id: string) => controller.switchAccount(id));
  handle("auth:remove", (id: string) => controller.removeAccount(id));
  handle("codex:list", (cwd: string, includeArchived?: boolean, force?: boolean) => controller.listCodexSessions(cwd, includeArchived, force));
  handle("codex:open", (id: string) => controller.openCodexSession(id));
  handle("codex:refresh", (id: string) => controller.refreshCodexSession(id));
  handle("codex:hide", (id: string, hidden?: boolean) => controller.hideCodexSession(id, hidden));
  handle("codex:continue", (id: string) => controller.continueCodexSession(id));
  handle("quota:get", (force?: boolean) => controller.getQuota(force));
  handle("providers:list", () => controller.listProviders());
  handle("providers:upsert", (input: CustomProviderInput) => controller.upsertProvider(input));
  handle("providers:remove", (id: string) => controller.removeProvider(id));
  handle("providers:test", (id: string) => controller.testProvider(id));
  handle("providers:pull-models", (id: string) => controller.pullProviderModels(id));
  handle("providers:probe-draft", (input: ProviderConnectionDraft) => controller.probeProviderDraft(input));
  handle("providers:discover-models", (input: ProviderConnectionDraft) => controller.discoverProviderModels(input));
  handle("providers:set-desktop-default", (modelId: string) => controller.setProviderDesktopDefault(modelId));
  handle("providers:set-cli-default", (modelId: string) => controller.setProviderCliDefault(modelId));
  handle("providers:reload", () => controller.reloadProviders());
  handle("automations:list", () => controller.listAutomations());
  handle("automations:create", (input: AutomationTaskInput) => controller.createAutomation(input));
  handle("automations:update", (id: string, patch: Partial<AutomationTaskInput>) => controller.updateAutomation(id, patch));
  handle("automations:delete", (id: string) => controller.deleteAutomation(id));
  handle("automations:pause", (id: string, paused: boolean) => controller.pauseAutomation(id, paused));
  handle("automations:run-now", (id: string) => controller.runAutomationNow(id));
  handle("automations:runs", (taskId?: string) => controller.listAutomationRuns(taskId));
  handle("automations:policy:get", () => controller.getAutomationGlobalPolicy());
  handle("automations:policy:update", (patch: Partial<AutomationGlobalPolicy>) => controller.updateAutomationGlobalPolicy(patch));
  handle("automations:policy:apply-all", () => controller.applyAutomationPolicyToAll());
  handle("automations:pending:respond", (id: string, approved: boolean) => controller.respondAutomationPending(id, approved));
  handle("automations:repair", () => controller.repairAutomationRegistrations());
  handle("automations:health:check", () => controller.checkAutomationHealth(false));
  handle("automations:health:repair", () => controller.checkAutomationHealth(true));
  handle("automations:clear-context", (id: string) => controller.clearAutomationContext(id));
  handle("draft:get", (key: string) => controller.getDraft(key));
  handle("draft:set", (key: string, text: string, capability?: ComposerCapabilitySelection) => controller.setDraft(key, text, capability));
  handle("draft:clear", (key: string) => controller.clearDraft(key));
  handle("prompt-history:list", (cwd: string) => controller.listPromptHistory(cwd));
  handle("prompt-history:append", (cwd: string, text: string) => controller.appendPromptHistory(cwd, text));
  handle("extensions:plugins:list", (force?: boolean) => controller.listPlugins(force));
  handle("extensions:plugins:details", (id: string) => controller.getPluginDetails(id));
  handle("extensions:plugins:preview", (source: string) => controller.previewPlugin(source));
  handle("extensions:plugins:action", (id: string, action: "enable" | "disable" | "update" | "uninstall" | "reload") => controller.pluginAction(id, action));
  handle("extensions:plugins:install", (source: string, trust: boolean, expectedFingerprint?: string) => controller.installPlugin(source, trust, expectedFingerprint));
  handle("extensions:marketplace:list", (force?: boolean) => controller.listMarketplace(force));
  handle("extensions:marketplace:install", (source: string, name: string, trust: boolean) => controller.installMarketplacePlugin(source, name, trust));
  handle("extensions:skills:list", () => controller.listSkills());
  handle("extensions:mcp:list", (force?: boolean) => controller.listMcpServers(force));
  handle("extensions:mcp:diagnose", (name?: string) => controller.diagnoseMcp(name));
  handle("extensions:mcp:toggle", (name: string, enabled: boolean) => controller.toggleMcp(name, enabled));
  handle("extensions:mcp:upsert", (input: McpServerInput) => controller.upsertMcp(input));
  handle("extensions:mcp:auth", (name: string) => controller.triggerMcpAuth(name));
  handle("extensions:mcp:remove", (name: string) => controller.removeMcp(name));
  handle("extensions:hooks:list", () => controller.listHooks());
  handle("extensions:reload", () => controller.reloadExtensions());
  handle("extensions:codex:scan", (force?: boolean) => controller.scanCodexPlugins(force));
  handle("extensions:codex:adapt", (id: string) => controller.adaptCodexPlugin(id));
  handle("extensions:codex:remove-adapter", (id: string) => controller.removeCodexPluginAdapter(id));
  handle("computer:capability", () => controller.getComputerCapability());
  handle("computer:list-apps", () => controller.listComputerApps());
  handle("computer:list-windows", (appId?: string) => controller.listComputerWindows(appId));
  handle("computer:start", (input: { sessionId: string; appId: string; windowId?: string }) => controller.startComputer(input));
  handle("computer:pause", (sessionId: string) => controller.pauseComputer(sessionId));
  handle("computer:resume", (sessionId: string) => controller.resumeComputer(sessionId));
  handle("computer:stop", (sessionId: string) => controller.stopComputer(sessionId));
  handle("computer:permission", (requestId: string, decision: "once" | "always" | "deny") => controller.respondComputerAppPermission(requestId, decision));
  handle("computer:risk", (requestId: string, approved: boolean) => controller.respondComputerRisk(requestId, approved));
  handle("computer:settings:get", () => controller.getComputerSettings());
  handle("computer:settings:update", (patch: Partial<ComputerUseSettings>) => controller.updateComputerSettings(patch));
  handle("cli:check-update", () => controller.checkCliUpdate());
  handle("cli:apply-update", () => controller.applyCliUpdate());
  handle("cli:update-history", () => controller.getCliUpdateHistory());
  handle("logs:export", () => controller.exportLogs());
}

function assertTrustedIpcSender(event: IpcMainInvokeEvent, window: BrowserWindow, policy: RendererTrustPolicy): void {
  const frame = event.senderFrame;
  const mainFrame = event.sender.mainFrame;
  if (window.isDestroyed() || event.sender.isDestroyed() || !frame || !mainFrame || !isTrustedRendererFrame({
    expectedWebContentsId: window.webContents.id,
    senderWebContentsId: event.sender.id,
    frameProcessId: frame.processId,
    frameRoutingId: frame.routingId,
    mainFrameProcessId: mainFrame.processId,
    mainFrameRoutingId: mainFrame.routingId,
    frameUrl: frame.url,
  }, policy)) {
    throw new Error("拒绝来自非受信任页面或子框架的 IPC 调用");
  }
}
