import {describe,expect,it,vi} from "vitest";
vi.mock("electron",()=>({app:{},clipboard:{},desktopCapturer:{},dialog:{},Menu:{},nativeImage:{},nativeTheme:{},Notification:class{},safeStorage:{},session:{},shell:{}}));
import {AppController} from "./app-controller";
import type {RemoteCommand} from "../shared/remote";
import {mkdtemp,rm} from "node:fs/promises";
import {tmpdir} from "node:os";
import {join} from "node:path";
const row={id:"session-one",cwd:"C:/demo",title:"demo",projectName:"demo",status:"idle",updatedAt:"",canSend:true};
const command:RemoteCommand={operationId:`${Date.now()}_00000000-0000-4000-8000-000000000001`,sessionId:row.id,action:"send",text:"continue"};
const adapter=()=>({working:false,needsUser:false});
function fixture(){const controller:any={focusedSessionId:"desktop-other",trustRemoteAttachments:vi.fn(async()=>undefined),remoteRuntime:vi.fn(async()=>({revision:"r",models:[],mode:"agent",effort:"",commands:[],mutable:true})),computer:{pendingForSession:()=>[]},requireRemoteSession:vi.fn(async()=>row),processes:{snapshot:vi.fn(()=>({cwd:row.cwd})),get:vi.fn(()=>adapter())},openSession:vi.fn(async()=>({sessionId:row.id,hydration:"ready"})),sendPrompt:vi.fn(async()=>undefined),enqueuePrompt:vi.fn(async()=>undefined),cancelSession:vi.fn(async()=>undefined),respondPermission:vi.fn(),remoteSnapshot:vi.fn(async()=>({pending:[]}))};return controller}
describe("Desktop remote execution owner",()=>{
 it("keeps message delivery behind attachment preparation in the original ACP order",async()=>{
   let release!:()=>void;const wait=new Promise<void>(resolve=>{release=resolve});const seen:string[]=[];
   const c:any={handleOrderedEvent:async(event:any)=>{if(event.type==="user-message")await wait;seen.push(event.type)}};
   const first=(AppController.prototype as any).handleEvent.call(c,{type:"user-message",sessionId:"s"});
   const status=(AppController.prototype as any).handleEvent.call(c,{type:"user-message-status",sessionId:"s"});
   await Promise.resolve();expect(seen).toEqual([]);release();await Promise.all([first,status]);
   expect(seen).toEqual(["user-message","user-message-status"]);
 });
 it("serializes effective configuration changes and rejects a second stale revision",async()=>{const c=fixture();const state={modelId:"old",mode:"agent",effort:""};c.configurationQueues=new Map();c.remoteConfigFlights=new Set();c.configurationMutation=(AppController.prototype as any).configurationMutation.bind(c);c.remoteRuntime=vi.fn(async()=>({revision:state.modelId==="old"?"a".repeat(64):"b".repeat(64),mutable:true}));c.setModelNow=vi.fn(async(_id:string,model:string)=>{await Promise.resolve();state.modelId=model});const change={...command,action:"configure",modelId:"new",revision:"a".repeat(64)};const results=await Promise.allSettled([(AppController.prototype as any).performRemoteCommand.call(c,change),(AppController.prototype as any).performRemoteCommand.call(c,{...change,modelId:"other"})]);expect(results[0]!.status).toBe("fulfilled");expect(results[1]!.status).toBe("rejected");expect(c.setModelNow).toHaveBeenCalledTimes(1);expect(state.modelId).toBe("new")});
 it("never changes the configuration of a queued or waiting turn",async()=>{const c=fixture();c.configurationQueues=new Map();c.remoteConfigFlights=new Set();c.configurationMutation=(AppController.prototype as any).configurationMutation.bind(c);c.remoteRuntime.mockResolvedValue({revision:"a".repeat(64),mutable:false,reason:"queue busy"});c.setModelNow=vi.fn();await expect((AppController.prototype as any).performRemoteCommand.call(c,{...command,action:"configure",modelId:"new",revision:"a".repeat(64)})).rejects.toThrow("queue busy");expect(c.setModelNow).not.toHaveBeenCalled()});
 it("uses the existing process and preserves Desktop focus and a native UUID message identity",async()=>{const c=fixture();await (AppController.prototype as any).performRemoteCommand.call(c,command);expect(c.openSession).not.toHaveBeenCalled();expect(c.sendPrompt).toHaveBeenCalledWith(row.id,"continue",[],command.operationId.slice(14),undefined,undefined,undefined);expect(c.focusedSessionId).toBe("desktop-other")});
 it("only resumes a cold conversation on explicit send and requests no focus activation",async()=>{const c=fixture();c.processes.snapshot.mockReturnValue(undefined);await (AppController.prototype as any).performRemoteCommand.call(c,command);expect(c.openSession).toHaveBeenCalledWith(row.cwd,row.id,false);expect(c.focusedSessionId).toBe("desktop-other")});
 it("queues a message while running and refuses to duplicate a missing original session",async()=>{const c=fixture();c.processes.get.mockReturnValue({...adapter(),working:true});expect(await (AppController.prototype as any).performRemoteCommand.call(c,command)).toEqual(expect.objectContaining({state:"queued"}));expect(c.sendPrompt).not.toHaveBeenCalled();c.processes.snapshot.mockReturnValue(undefined);c.openSession.mockResolvedValue({sessionId:"another",hydration:"ready"});await expect((AppController.prototype as any).performRemoteCommand.call(c,command)).rejects.toThrow("原会话")});
 it("does not answer a stale permission after the other device resolved it",async()=>{const c=fixture();await expect((AppController.prototype as any).performRemoteCommand.call(c,{...command,action:"permission",requestId:"p",optionId:"yes"})).rejects.toThrow("已处理");expect(c.respondPermission).not.toHaveBeenCalled()});
 it("only creates inside a known project and never activates the Desktop tab",async()=>{const c=fixture();c.remoteOptions=vi.fn(async()=>({workspaces:[{id:"known",profiles:[{id:"profile"}]}]}));c.settingsStore={get:vi.fn(async()=>({activeWorkspace:row.cwd,recentWorkspaces:[]}))};c.discoverWorkspaces=vi.fn(async()=>[]);c.createSession=vi.fn(async()=>({sessionId:"created"}));c.invalidateRemoteList=vi.fn();const {createHash}=await import("node:crypto");const key=createHash("sha256").update(row.cwd.toLowerCase()).digest("hex").slice(0,24);c.remoteOptions.mockResolvedValue({workspaces:[{id:key,profiles:[{id:"profile"}]}]});await expect((AppController.prototype as any).performRemoteCommand.call(c,{...command,action:"create",sessionId:"new",workspaceId:"unknown"})).rejects.toThrow("项目");await expect((AppController.prototype as any).performRemoteCommand.call(c,{...command,action:"create",sessionId:"new",workspaceId:key,profileId:"other"})).rejects.toThrow("配置档");const value=await (AppController.prototype as any).performRemoteCommand.call(c,{...command,action:"create",sessionId:"new",workspaceId:key,profileId:"profile"});expect(value.resultSessionId).toBe("created");expect(c.createSession).toHaveBeenCalledWith(expect.objectContaining({workspacePath:row.cwd,profileId:"profile"}),false);expect(c.focusedSessionId).toBe("desktop-other")});
 it("renames and archives existing records without starting execution",async()=>{const c=fixture();c.renameSession=vi.fn();c.archiveSession=vi.fn();c.invalidateRemoteList=vi.fn();await (AppController.prototype as any).performRemoteCommand.call(c,{...command,action:"rename",title:"Updated"});await (AppController.prototype as any).performRemoteCommand.call(c,{...command,action:"archive",archived:true});expect(c.renameSession).toHaveBeenCalledWith(row.id,"Updated");expect(c.archiveSession).toHaveBeenCalledWith(row.id,true);expect(c.openSession).not.toHaveBeenCalled();expect(c.sendPrompt).not.toHaveBeenCalled()});
 it("marks an unread session read only on an explicit phone open of the latest page",async()=>{const c=fixture();c.requireRemoteSession=vi.fn(async()=>({...row,status:"unread"}));c.catalog={markRead:vi.fn(async()=>undefined)};c.inspectSession=vi.fn(async()=>({events:[]}));
  expect((await AppController.prototype.remoteSnapshot.call(c,row.id)).session.status).toBe("unread");expect(c.catalog.markRead).not.toHaveBeenCalled();
  await AppController.prototype.remoteSnapshot.call(c,row.id,5,undefined,true);expect(c.catalog.markRead).not.toHaveBeenCalled();
  const opened=await AppController.prototype.remoteSnapshot.call(c,row.id,undefined,undefined,true);expect(c.catalog.markRead).toHaveBeenCalledWith(row.id);expect(opened.session.status).toBe("idle");expect(c.openSession).not.toHaveBeenCalled()});
 it("reads bounded history without resuming a session or marking it read",async()=>{const c=fixture();c.inspectSession=vi.fn(async()=>({events:Array.from({length:3000},(_,index)=>({type:"message-chunk",sessionId:row.id,text:String(index)}))}));const result=await AppController.prototype.remoteSnapshot.call(c,row.id);expect(result.before).toBe(1000);expect(result.events).toHaveLength(2000);expect(result.events[0]).toMatchObject({remoteIndex:1000});expect(c.openSession).not.toHaveBeenCalled();expect(c.sendPrompt).not.toHaveBeenCalled();expect(c.focusedSessionId).toBe("desktop-other")});
});

describe("remote catalog and scheduled overrides",()=>{
 it("keeps stale project paths from poisoning model discovery and omits unavailable creation targets",async()=>{
  const c:any={settingsStore:{get:async()=>({activeWorkspace:"C:/valid",recentWorkspaces:["C:/removed"],defaultModel:"obsolete",defaultEffort:"",defaultMode:"agent"})},discoverWorkspaces:async()=>[],deletingWorkspaces:new Set(),listExecutionProfiles:vi.fn(async(cwd:string)=>{if(cwd.endsWith("removed"))throw Object.assign(Error("gone"),{code:"ENOENT"});return []}),listModelCatalog:async()=>[{modelId:"current",name:"Current",defaultForCli:true}],listProviders:async()=>[]};
  const options=await AppController.prototype.remoteOptions.call(c);expect(options.workspaces.map(row=>row.path)).toEqual(["C:/valid"]);expect(options.models?.[0]?.modelId).toBe("current");expect(options.defaults?.modelId).toBe("current");expect(options.notices?.join(" ")).toContain("部分项目");
  c.discoverWorkspaces=vi.fn(async()=>{throw Error("workspace scan should not run")});c.listExecutionProfiles.mockClear();
  const models=await AppController.prototype.remoteOptions.call(c,true,true);expect(models.models).toHaveLength(1);expect(c.discoverWorkspaces).not.toHaveBeenCalled();expect(c.listExecutionProfiles).not.toHaveBeenCalled();
 });
 it("loads the selected question and its answer, rather than a page ending at the question",async()=>{
  const c=fixture();c.inspectSession=vi.fn(async()=>({events:[{type:"user-message",text:"first"},{type:"message-chunk",text:"first answer"},{type:"user-message",text:"target"},{type:"turn-started"},{type:"message-chunk",text:"target answer"},{type:"turn-completed"},{type:"user-message",text:"latest"}]}));
  const result=await AppController.prototype.remoteSnapshot.call(c,row.id,undefined,2);expect(result.events.map(event=>event.type)).toEqual(["user-message","turn-started","message-chunk","turn-completed"]);expect(result.events[0]).toMatchObject({remoteIndex:2,text:"target"});expect(result.events[2]).toMatchObject({text:"target answer"});expect(c.openSession).not.toHaveBeenCalled();
 });
 it("returns options before a slow CLI probe and replaces obsolete native models after its declaration",async()=>{
   const cwd=await mkdtemp(join(tmpdir(),"grok-catalog-"));let finish!:(models:any[])=>void;
   const models=new Promise<any[]>(resolve=>{finish=resolve});
   const c:any=Object.create(AppController.prototype);
   Object.assign(c,{settingsStore:{get:async()=>({activeWorkspace:cwd,recentWorkspaces:[],defaultModel:"old",defaultEffort:"",defaultMode:"agent"})},discoverWorkspaces:async()=>[],deletingWorkspaces:new Set(),listExecutionProfiles:async()=>[],processes:{listKnownModels:()=>[{modelId:"old",name:"Old"}],probeModelCatalog:vi.fn(()=>models)},providers:{list:async()=>[]},log:{log:async()=>{}},modelCatalog:[],modelCatalogProbedAt:0,modelCatalogAttemptedAt:0});
   try{const options=await c.remoteOptions(true);expect(options.modelCatalog.refreshing).toBe(true);expect(options.models).toContainEqual(expect.objectContaining({modelId:"old"}));finish([{modelId:"current",name:"Current"}]);const fresh=await c.listModelCatalog(true);expect(fresh.map((model:any)=>model.modelId)).toEqual(["current"]);expect(c.processes.probeModelCatalog).toHaveBeenCalledTimes(1);expect((await c.listModelCatalog(false)).map((model:any)=>model.modelId)).toEqual(["current"])}finally{finish([]);await rm(cwd,{recursive:true,force:true})}
 });
 it("retains known projects and models when the Provider catalog fails",async()=>{const c:any={settingsStore:{get:async()=>({activeWorkspace:"C:/demo",recentWorkspaces:[],defaultEffort:"low",defaultMode:"agent"})},discoverWorkspaces:async()=>[],deletingWorkspaces:new Set(),listExecutionProfiles:async()=>[],listModelCatalog:async()=>[{modelId:"native",name:"Native"}],listProviders:async()=>{throw Error("invalid external URL")}};const options=await AppController.prototype.remoteOptions.call(c);expect(options.workspaces).toHaveLength(1);expect(options.models).toHaveLength(1);expect(options.notices?.[0]).toContain("Provider");expect(options.imageModels).toEqual([]);});
 it("freezes explicit schedule overrides without dropping the selected profile tools",async()=>{const c:any={compileExecutionProfile:vi.fn(async()=>({profile:{id:"preset",allowTools:["read_file"],mode:"auto",modelId:"old",effort:"low"}})),applyExecutionProfileToAutomation:async(input:any)=>input,automations:{createOne:vi.fn(async(input:any)=>input)}};const input:any={workspace:"C:/demo",executionProfileId:"preset",destination:"standalone",profile:{modelId:"old",effort:"low",mode:"agent",permissionPolicy:"agent",computerEnabled:false}};const value=await AppController.prototype.createRemoteAutomation.call(c,input,{modelId:"new",effort:"high",mode:"agent"});expect(value.frozenExecutionProfile).toMatchObject({modelId:"new",effort:"high",mode:"agent",allowTools:["read_file"]});expect(value.profile.modelId).toBe("new");});
});
